{
  "type" : "record",
  "name" : "JobVisibilityJobSeenEvent",
  "namespace" : "com.indeed.signals.schema.iplusatsplugin",
  "fields" : [ {
    "name" : "commonDetails",
    "type" : [ "null", {
      "type" : "record",
      "name" : "CommonEventDetails",
      "namespace" : "com.indeed.signals.common",
      "fields" : [ {
        "name" : "ipAddress",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    } ]
  }, {
    "name" : "atsPluginCommon",
    "type" : {
      "type" : "record",
      "name" : "CommonLogEntryFields",
      "fields" : [ {
        "name" : "sessionId",
        "type" : "string"
      }, {
        "name" : "userAgent",
        "type" : "string"
      }, {
        "name" : "oauthClientId",
        "type" : "string"
      }, {
        "name" : "atsKey",
        "type" : "string"
      }, {
        "name" : "accountKey",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "advertiserKey",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    }
  }, {
    "name" : "browser",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Browser",
      "symbols" : [ "CHROME", "FIREFOX", "SAFARI", "EDGE" ]
    } ],
    "default" : null
  }, {
    "name" : "os",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "OS",
      "symbols" : [ "WINDOWS", "MACOS", "IOS", "ANDROID" ]
    } ],
    "default" : null
  }, {
    "name" : "deviceType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "DeviceType",
      "symbols" : [ "MOBILE", "TABLET" ]
    } ],
    "default" : null
  }, {
    "name" : "onehost",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "BooleanTag",
      "symbols" : [ "TRUE", "FALSE" ]
    } ],
    "default" : null
  }, {
    "name" : "indeedEligible",
    "type" : "boolean"
  }, {
    "name" : "indeedplusEligible",
    "type" : "boolean"
  }, {
    "name" : "isSponsored",
    "type" : "boolean"
  }, {
    "name" : "isJipgPassed",
    "type" : "boolean"
  }, {
    "name" : "employerJobId",
    "type" : "string"
  }, {
    "name" : "plugin",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "messagingTagIds",
    "type" : [ "null", {
      "type" : "array",
      "items" : "int"
    } ],
    "default" : null
  }, {
    "name" : "messagingTagNames",
    "type" : [ "null", {
      "type" : "array",
      "items" : "string"
    } ],
    "default" : null
  } ],
  "logEntryType" : "iplus_atsplugin_jobvisibility_job_seen"
}