{
  "type" : "record",
  "name" : "JobVisibilityButtonLoad",
  "namespace" : "com.indeed.signals.schema.iplusatsplugin",
  "fields" : [ {
    "name" : "commonDetails",
    "type" : [ "null", {
      "type" : "record",
      "name" : "CommonEventDetails",
      "namespace" : "com.indeed.signals.common",
      "fields" : [ {
        "name" : "ipAddress",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    } ]
  }, {
    "name" : "atsPluginCommon",
    "type" : {
      "type" : "record",
      "name" : "CommonLogEntryFields",
      "fields" : [ {
        "name" : "sessionId",
        "type" : "string"
      }, {
        "name" : "userAgent",
        "type" : "string"
      }, {
        "name" : "oauthClientId",
        "type" : "string"
      }, {
        "name" : "atsKey",
        "type" : "string"
      }, {
        "name" : "accountKey",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "advertiserKey",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    }
  }, {
    "name" : "browser",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Browser",
      "symbols" : [ "CHROME", "FIREFOX", "SAFARI", "EDGE" ]
    } ],
    "default" : null
  }, {
    "name" : "os",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "OS",
      "symbols" : [ "WINDOWS", "MACOS", "IOS", "ANDROID" ]
    } ],
    "default" : null
  }, {
    "name" : "deviceType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "DeviceType",
      "symbols" : [ "MOBILE", "TABLET" ]
    } ],
    "default" : null
  }, {
    "name" : "onehost",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "BooleanTag",
      "symbols" : [ "TRUE", "FALSE" ]
    } ],
    "default" : null
  }, {
    "name" : "buttonType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "ButtonType",
      "symbols" : [ "STATIC", "DYNAMIC" ]
    } ]
  }, {
    "name" : "renderDurationMs",
    "type" : [ "null", {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    } ],
    "default" : null
  }, {
    "name" : "indeedEligible",
    "type" : [ "null", "boolean" ],
    "default" : null
  }, {
    "name" : "indeedplusEligible",
    "type" : [ "null", "boolean" ],
    "default" : null
  }, {
    "name" : "isSponsored",
    "type" : [ "null", "boolean" ],
    "default" : null
  }, {
    "name" : "isJipgPassed",
    "type" : [ "null", "boolean" ],
    "default" : null
  }, {
    "name" : "employerJobId",
    "type" : [ "null", "string" ],
    "default" : null
  } ],
  "unstable_metrics" : [ {
    "name" : "IPlusAtsPlugin.JobVisibility.buttonRendering",
    "type" : "distribution",
    "value" : "renderDurationMs",
    "tags" : [ "browser", "os", "deviceType", "onehost", "buttonType" ]
  } ],
  "logEntryType" : "iplus_atsplugin_jobvisibility_button_rendering"
}