{
  "type" : "record",
  "name" : "GnavJSError",
  "namespace" : "com.indeed.signals.schema.globalnav",
  "fields" : [ {
    "name" : "hostAppTk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "from",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "toString",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "message",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "stack",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "name",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "parentLogId",
    "type" : [ "null", "string" ],
    "default" : null
  } ]
}