{
  "type" : "record",
  "name" : "PageInteractive",
  "namespace" : "com.indeed.signals.schema.ipluspublisherplugin",
  "fields" : [ {
    "name" : "commonDetails",
    "type" : [ "null", {
      "type" : "record",
      "name" : "CommonEventDetails",
      "namespace" : "com.indeed.signals.common",
      "fields" : [ {
        "name" : "ipAddress",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    } ]
  }, {
    "name" : "publisherPluginCommon",
    "type" : {
      "type" : "record",
      "name" : "CommonLogEntryFields",
      "fields" : [ {
        "name" : "sessionId",
        "type" : [ "null", "string" ]
      }, {
        "name" : "userAgent",
        "type" : [ "null", "string" ]
      }, {
        "name" : "partnerAppId",
        "type" : [ "null", "string" ]
      }, {
        "name" : "placementId",
        "type" : [ "null", "string" ]
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "proctorGroups",
        "type" : [ "null", {
          "type" : "array",
          "items" : "string"
        } ],
        "default" : null
      } ]
    }
  }, {
    "name" : "browser",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Browser",
      "symbols" : [ "CHROME", "FIREFOX", "SAFARI", "EDGE" ]
    } ],
    "default" : null
  }, {
    "name" : "os",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "OS",
      "symbols" : [ "WINDOWS", "MACOS", "IOS", "ANDROID" ]
    } ],
    "default" : null
  }, {
    "name" : "deviceType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "DeviceType",
      "symbols" : [ "MOBILE", "TABLET" ]
    } ],
    "default" : null
  }, {
    "name" : "jobResultRenderTimeMillis",
    "type" : [ "null", {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    } ],
    "default" : null
  }, {
    "name" : "totalTimeMillis",
    "type" : [ "null", {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    } ],
    "default" : null
  }, {
    "name" : "turnstileDurationMillis",
    "type" : [ "null", {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    } ],
    "default" : null
  }, {
    "name" : "botDetectionResult",
    "type" : {
      "type" : "enum",
      "name" : "BotDetectionResult",
      "symbols" : [ "PASS", "FAIL", "NEVER" ]
    }
  }, {
    "name" : "result",
    "type" : {
      "type" : "enum",
      "name" : "Result",
      "symbols" : [ "SUCCESS", "FAILURE" ]
    }
  }, {
    "name" : "numJobs",
    "type" : [ "null", "int" ]
  }, {
    "name" : "numInitialDisplayedJobs",
    "type" : [ "null", "int" ],
    "default" : null
  } ],
  "unstable_metrics" : [ {
    "name" : "IPlusPublisherPlugin.JobSearch.pageInteractive",
    "type" : "distribution",
    "value" : "totalTimeMillis",
    "tags" : [ "botDetectionResult", "result", "browser", "os", "deviceType" ]
  }, {
    "name" : "IPlusPublisherPlugin.JobSearch.pageInteractive.jobResultRender",
    "type" : "distribution",
    "value" : "jobResultRenderTimeMillis",
    "tags" : [ "botDetectionResult", "result", "browser", "os", "deviceType" ]
  }, {
    "name" : "IPlusPublisherPlugin.JobSearch.pageInteractive.turnstileDuration",
    "type" : "distribution",
    "value" : "turnstileDurationMillis",
    "tags" : [ "botDetectionResult", "result", "browser", "os", "deviceType" ]
  } ],
  "logEntryType" : "iplus_publisherplugin_jobsearch_pageinteractive"
}