{
  "type" : "record",
  "name" : "Feedback",
  "namespace" : "com.indeed.signals.schema.jspremium",
  "fields" : [ {
    "name" : "hostId",
    "type" : "string"
  }, {
    "name" : "provider",
    "type" : "string"
  }, {
    "name" : "accountId",
    "type" : "long"
  }, {
    "name" : "country",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "ctaType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "CTAType",
      "symbols" : [ "PRO", "PREMIUM" ],
      "default" : "PRO"
    } ],
    "default" : null
  }, {
    "name" : "action",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Action",
      "symbols" : [ "UNKNOWN", "BUTTON_CLICK", "RESULT" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "parentLogId",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "feedbackText",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "feedbackResponse",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "FeedbackResponse",
      "symbols" : [ "UNKNOWN", "YES", "NO" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "smileyRatingsFeedbackResponse",
    "type" : [ "null", "int" ],
    "default" : null
  }, {
    "name" : "jobKey",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "mobtk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "pageId",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "isPrivileged",
    "type" : [ "null", "boolean" ],
    "default" : null
  }, {
    "name" : "moduleType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "ModuleType",
      "symbols" : [ "UNKNOWN", "CTA", "APPLICANT_INSIGHTS", "TOP_APPLICANT", "TOP_CHOICE", "PRO_FEEDBACK", "ASSISTED_APPLY_V2", "AUTO_APPLY" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "proctorGroups",
    "type" : [ "null", {
      "type" : "array",
      "items" : "string"
    } ],
    "default" : null
  }, {
    "name" : "accountKey",
    "type" : [ "null", "string" ],
    "default" : null
  } ],
  "logEntryType" : "jsPremiumFeedback"
}