{
  "type" : "record",
  "name" : "CommonJSOnboardingDetails",
  "namespace" : "com.indeed.signals.schema.jsonboarding",
  "fields" : [ {
    "name" : "platformType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "PlatformType",
      "symbols" : [ "APP_ANDROID", "APP_IOS", "APP_OTHER", "MOBILE_ANDROID", "MOBILE_IOS", "MOBILE_OTHER", "DESKTOP", "OTHER" ],
      "default" : "OTHER"
    } ]
  }, {
    "name" : "proctorGroups",
    "type" : {
      "type" : "array",
      "items" : "string"
    }
  }, {
    "name" : "accountId",
    "type" : [ "null", "string" ]
  }, {
    "name" : "userAgent",
    "type" : [ "null", "string" ]
  }, {
    "name" : "country",
    "type" : [ "null", "string" ]
  }, {
    "name" : "language",
    "type" : [ "null", "string" ]
  }, {
    "name" : "onboardingFlowId",
    "type" : [ "null", "string" ]
  }, {
    "name" : "originLogId",
    "type" : [ "null", "string" ]
  }, {
    "name" : "page",
    "type" : [ "null", "string" ]
  }, {
    "name" : "client",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Client",
      "symbols" : [ "jsonboardingwebapp", "jsonboardingreactnative" ]
    } ],
    "default" : null
  }, {
    "name" : "countryCode",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "CountryCode",
      "symbols" : [ "UNKNOWN", "AE", "AQ", "AR", "AT", "AU", "BE", "BH", "BR", "CA", "CH", "CL", "CN", "CO", "CR", "CZ", "DE", "DK", "EC", "EG", "ES", "FI", "FR", "GB", "GR", "HK", "HU", "ID", "IE", "IL", "IN", "IT", "JP", "KR", "KW", "LU", "MA", "MX", "MY", "NG", "NL", "NO", "NZ", "OM", "PA", "PE", "PH", "PK", "PL", "PT", "QA", "RO", "RU", "SA", "SE", "SG", "TH", "TR", "TW", "UA", "US", "UY", "VE", "VN", "ZA" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "languageCode",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "LanguageCode",
      "symbols" : [ "UNKNOWN", "ar", "bn", "cs", "da", "de", "el", "en", "es", "fi", "fr", "hi", "hu", "in", "it", "iw", "ja", "jp", "ko", "mr", "ms", "nl", "no", "pl", "pt", "ro", "ru", "sv", "ta", "te", "th", "tr", "uk", "us", "vi", "zh", "zz" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  } ]
}