{
  "type" : "record",
  "name" : "JsOnboardingMonitoringEvent",
  "namespace" : "com.indeed.signals.schema.jsonboarding",
  "fields" : [ {
    "name" : "client",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Client",
      "symbols" : [ "jsonboardingwebapp", "jsonboardingreactnative" ]
    } ],
    "default" : null
  }, {
    "name" : "countryCode",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "CountryCode",
      "symbols" : [ "UNKNOWN", "AE", "AQ", "AR", "AT", "AU", "BE", "BH", "BR", "CA", "CH", "CL", "CN", "CO", "CR", "CZ", "DE", "DK", "EC", "EG", "ES", "FI", "FR", "GB", "GR", "HK", "HU", "ID", "IE", "IL", "IN", "IT", "JP", "KR", "KW", "LU", "MA", "MX", "MY", "NG", "NL", "NO", "NZ", "OM", "PA", "PE", "PH", "PK", "PL", "PT", "QA", "RO", "RU", "SA", "SE", "SG", "TH", "TR", "TW", "UA", "US", "UY", "VE", "VN", "ZA" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "elementName",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "ElementName",
      "symbols" : [ "BACK_BUTTON", "BACK_OR_CLOSE_BUTTON", "CLOSE_BUTTON", "DELETE_BUTTON", "DETECT_LOCATION_BUTTON", "EDIT_JOBTITLE_BUTTON", "EDIT_JOBTYPE_BUTTON", "EDIT_LOCATION_BUTTON", "EDIT_PAY_BUTTON", "EXIT_BUTTON", "NOT_NOW_BUTTON", "OPEN_TO_ANYTHING_BUTTON", "REVIEW_RESUME_BUTTON", "SAVE_NEXT_BUTTON", "SKIP_BUTTON", "UPLOAD_BUTTON", "UNKNOWN" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "eventType",
    "type" : {
      "type" : "enum",
      "name" : "MonitoringEventType",
      "symbols" : [ "CLICK", "CROWTAXO_START_PRELOAD_DATA", "IMPRESSION", "ON_COMPLETE_ONBOARDING", "ON_EXIT", "TRIGGER_PUSH_PRIMER", "ZERO_MAX_EXPECTED_PAGE_ROUTES", "UNKNOWN" ],
      "default" : "UNKNOWN"
    }
  }, {
    "name" : "originLogId",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "pageName",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "PageName",
      "symbols" : [ "UNKNOWN", "LOCATION", "MINIMUM_PAY", "DESIRED_JOB", "RECENT_JOB", "CROWTAXO_SKILLS", "CROWTAXO_CREDENTIALS", "JOB_TYPES", "GENERALIST_CREDENTIALS", "GENERALIST_EDUCATION", "GENERALIST_SKILLS", "GENERALIST_WORK_AREAS", "PUSH_PROMO", "WORK_WELL_BEING", "REMOTE_WORK_PREFERENCE", "SOURCING_OPT_IN", "RESUME_GLOWUP_OPT_IN", "RESUME_GLOWUP_REVIEW_SUGGESTIONS", "RESUME_UPLOAD", "RESUME_GLOWUP_CS_CHAT", "RESUME_GLOWUP_CS_REVIEW", "SUMMARY" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "platformType",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "PlatformType",
      "symbols" : [ "APP_ANDROID", "APP_IOS", "APP_OTHER", "MOBILE_ANDROID", "MOBILE_IOS", "MOBILE_OTHER", "DESKTOP", "OTHER" ],
      "default" : "OTHER"
    } ],
    "default" : null
  }, {
    "name" : "variant",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "Variant",
      "symbols" : [ "page", "section", "component", "element" ],
      "default" : "element"
    } ],
    "default" : null
  }, {
    "name" : "withError",
    "type" : [ "null", "boolean" ],
    "default" : null
  } ],
  "unstable_metrics" : [ {
    "name" : "onboarding.jsOnboardingMonitoringEvent",
    "tags" : [ "client", "countryCode", "elementName", "eventType", "pageName", "platformType", "variant", "withError" ]
  } ],
  "logEntryType" : "jsOnboardingMonitoringEvent"
}