{
  "type" : "enum",
  "name" : "PageName",
  "namespace" : "com.indeed.signals.schema.jsonboarding",
  "symbols" : [ "UNKNOWN", "LOCATION", "MINIMUM_PAY", "DESIRED_JOB", "RECENT_JOB", "CROWTAXO_SKILLS", "CROWTAXO_CREDENTIALS", "JOB_TYPES", "GENERALIST_CREDENTIALS", "GENERALIST_EDUCATION", "GENERALIST_SKILLS", "GENERALIST_WORK_AREAS", "PUSH_PROMO", "WORK_WELL_BEING", "REMOTE_WORK_PREFERENCE", "SOURCING_OPT_IN", "RESUME_GLOWUP_OPT_IN", "RESUME_GLOWUP_REVIEW_SUGGESTIONS", "RESUME_UPLOAD", "RESUME_GLOWUP_CS_CHAT", "RESUME_GLOWUP_CS_REVIEW", "SUMMARY" ],
  "default" : "UNKNOWN"
}