{
  "type" : "record",
  "name" : "RNVJApplyButtonShowEventV3",
  "namespace" : "com.indeed.signals.schema.viewjob",
  "fields" : [ {
    "name" : "deviceProperties",
    "type" : {
      "type" : "record",
      "name" : "RNDevicePropertiesV4",
      "namespace" : "com.indeed.signals.schema.reactnative",
      "fields" : [ {
        "name" : "platform",
        "type" : {
          "type" : "enum",
          "name" : "RNPlatformsV4",
          "symbols" : [ "ios", "android" ]
        }
      }, {
        "name" : "osVersion",
        "type" : "string"
      }, {
        "name" : "appName",
        "type" : {
          "type" : "enum",
          "name" : "RNAppsV4",
          "symbols" : [ "jsma", "ema" ]
        }
      }, {
        "name" : "nativeAppVersion",
        "type" : "string"
      }, {
        "name" : "rnLibraryVersion",
        "type" : "string"
      }, {
        "name" : "rnAppBundleVersion",
        "type" : "string"
      }, {
        "name" : "manufacturer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "model",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "brand",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "systemName",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "buildVariant",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "environment",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "variant",
        "type" : [ "null", {
          "type" : "enum",
          "name" : "BuildVariant",
          "symbols" : [ "debug", "release" ]
        } ],
        "default" : null
      }, {
        "name" : "env",
        "type" : [ "null", {
          "type" : "enum",
          "name" : "Environment",
          "symbols" : [ "qa", "prod" ]
        } ],
        "default" : null
      }, {
        "name" : "isIpad",
        "type" : "boolean"
      } ]
    }
  }, {
    "name" : "jobkey",
    "type" : "string"
  }, {
    "name" : "tk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "buttonType",
    "type" : {
      "type" : "enum",
      "name" : "RNApplyButtonTypeV3",
      "symbols" : [ "indeedApply", "thirdParty" ]
    }
  }, {
    "name" : "srcWidth",
    "type" : [ "null", "long" ],
    "doc" : "screen width",
    "default" : null
  }, {
    "name" : "srcHeight",
    "type" : [ "null", "long" ],
    "doc" : "screen height",
    "default" : null
  }, {
    "name" : "iaButtonY",
    "type" : [ "null", "long" ],
    "doc" : "Y position of IA button in the screen",
    "default" : null
  }, {
    "name" : "iaButtonX",
    "type" : [ "null", "long" ],
    "doc" : "X position of IA button in the screen",
    "default" : null
  }, {
    "name" : "iaButtonHeight",
    "type" : [ "null", "long" ],
    "doc" : "height of IA button in the screen",
    "default" : null
  }, {
    "name" : "iaButtonWidth",
    "type" : [ "null", "long" ],
    "doc" : "width of IA button in the screen",
    "default" : null
  } ],
  "logEntryType" : "rnvjApplyButtonShowEvent"
}