package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ayf {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final to5 D;
    public static final dz5 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final to5 I;
    public static final dz5 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final to5 N;
    public static final dz5 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final to5 S;
    public static final dz5 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final to5 X;
    public static final dz5 Y;
    public static final long Z;
    public static final dz5 a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final to5 c0;
    public static final long d;
    public static final dz5 d0;
    public static final to5 e;
    public static final long e0;
    public static final dz5 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final to5 h0;
    public static final long i;
    public static final dz5 i0;
    public static final to5 j;
    public static final long j0;
    public static final dz5 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final to5 m0;
    public static final long n;
    public static final dz5 n0;
    public static final to5 o;
    public static final long o0;
    public static final dz5 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final to5 r0;
    public static final long s;
    public static final dz5 s0;
    public static final to5 t;
    public static final long t0;
    public static final dz5 u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final to5 w0;
    public static final long x;
    public static final to5 y;
    public static final dz5 z;

    static {
        dz5 dz5Var = jzf.b;
        a = dz5Var;
        b = hh2.s(24.0d);
        c = hh2.t(16);
        d = hh2.s(0.5d);
        to5 to5Var = jzf.d;
        e = to5Var;
        f = dz5Var;
        g = hh2.s(20.0d);
        h = hh2.t(14);
        i = hh2.s(0.2d);
        j = to5Var;
        k = dz5Var;
        l = hh2.s(16.0d);
        m = hh2.t(12);
        n = hh2.s(0.4d);
        o = to5Var;
        dz5 dz5Var2 = jzf.a;
        p = dz5Var2;
        q = hh2.s(64.0d);
        r = hh2.t(57);
        long jS = hh2.s(0.2d);
        hh2.l(jS);
        s = hh2.y(jS & 1095216660480L, -bkf.c(jS));
        t = to5Var;
        u = dz5Var2;
        v = hh2.s(52.0d);
        w = hh2.t(45);
        x = hh2.s(0.0d);
        y = to5Var;
        z = dz5Var2;
        A = hh2.s(44.0d);
        B = hh2.t(36);
        C = hh2.s(0.0d);
        D = to5Var;
        E = dz5Var2;
        F = hh2.s(40.0d);
        G = hh2.t(32);
        H = hh2.s(0.0d);
        I = to5Var;
        J = dz5Var2;
        K = hh2.s(36.0d);
        L = hh2.t(28);
        M = hh2.s(0.0d);
        N = to5Var;
        O = dz5Var2;
        P = hh2.s(32.0d);
        Q = hh2.t(24);
        R = hh2.s(0.0d);
        S = to5Var;
        T = dz5Var;
        U = hh2.s(20.0d);
        V = hh2.t(14);
        W = hh2.s(0.1d);
        to5 to5Var2 = jzf.c;
        X = to5Var2;
        Y = dz5Var;
        Z = hh2.s(16.0d);
        a0 = hh2.t(12);
        b0 = hh2.s(0.5d);
        c0 = to5Var2;
        d0 = dz5Var;
        e0 = hh2.s(16.0d);
        f0 = hh2.t(11);
        g0 = hh2.s(0.5d);
        h0 = to5Var2;
        i0 = dz5Var2;
        j0 = hh2.s(28.0d);
        k0 = hh2.t(22);
        l0 = hh2.s(0.0d);
        m0 = to5Var;
        n0 = dz5Var;
        o0 = hh2.s(24.0d);
        p0 = hh2.t(16);
        q0 = hh2.s(0.2d);
        r0 = to5Var2;
        s0 = dz5Var;
        t0 = hh2.s(20.0d);
        u0 = hh2.t(14);
        v0 = hh2.s(0.1d);
        w0 = to5Var2;
    }
}
