package defpackage;

import com.datadog.android.rum.internal.debug.UiRumDebugListener;
import com.google.android.gms.common.util.VisibleForTesting;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/* JADX INFO: loaded from: classes2.dex */
@VisibleForTesting
public final class djh {
    public static final svh<Long> A;
    public static final svh<Boolean> A0;
    public static final svh<Long> B;
    public static final svh<Boolean> B0;
    public static final svh<Integer> C;
    public static final svh<Boolean> C0;
    public static final svh<Long> D;
    public static final svh<Boolean> D0;
    public static final svh<Integer> E;
    public static final svh<Boolean> E0;
    public static final svh<Integer> F;
    public static final svh<Boolean> F0;
    public static final svh<Integer> G;
    public static final svh<Boolean> G0;
    public static final svh<Integer> H;
    public static final svh<Boolean> H0;
    public static final svh<Integer> I;
    public static final svh<Boolean> I0;
    public static final svh<Long> J;
    public static final svh<Boolean> J0;
    public static final svh<Boolean> K;
    public static final svh<Boolean> K0;
    public static final svh<String> L;
    public static final svh<Boolean> L0;
    public static final svh<Long> M;
    public static final svh<Boolean> M0;
    public static final svh<Integer> N;
    public static final svh<Boolean> N0;
    public static final svh<Double> O;
    public static final svh<Boolean> O0;
    public static final svh<Integer> P;
    public static final svh<Boolean> P0;
    public static final svh<Integer> Q;
    public static final svh<Long> Q0;
    public static final svh<Boolean> R;
    public static final svh<Boolean> R0;
    public static final svh<Boolean> S;
    public static final svh<Boolean> T;
    public static final svh<Boolean> U;
    public static final svh<Boolean> V;
    public static final svh<Boolean> W;
    public static final svh<Boolean> X;
    public static final svh<Boolean> Y;
    public static final svh<Boolean> Z;
    public static final svh<Boolean> a0;
    public static final svh<Boolean> b0;
    public static final svh<Boolean> c0;
    public static final svh<Boolean> d0;
    public static final svh<Boolean> e0;
    public static final svh<Boolean> f0;
    public static final svh<Boolean> g0;
    public static final svh<Boolean> h0;
    public static final svh<Boolean> i0;
    public static final svh<Boolean> j0;
    public static final svh<Boolean> k0;
    public static final svh<Boolean> l0;
    public static final svh<Boolean> m0;
    public static final svh<Boolean> n0;
    public static final svh<Boolean> o0;
    public static final svh<Boolean> p0;
    public static final svh<Boolean> q0;
    public static final svh<Boolean> r0;
    public static final svh<Boolean> s0;
    public static final svh<Long> t;
    public static final svh<Boolean> t0;
    public static final svh<Long> u;
    public static final svh<Boolean> u0;
    public static final svh<Long> v;
    public static final svh<Boolean> v0;
    public static final svh<Long> w;
    public static final svh<Boolean> w0;
    public static final svh<Long> x;
    public static final svh<Boolean> x0;
    public static final svh<Long> y;
    public static final svh<Boolean> y0;
    public static final svh<Long> z;
    public static final svh<Boolean> z0;
    public static final List<svh<?>> a = Collections.synchronizedList(new ArrayList());
    public static final Set<svh<?>> b = Collections.synchronizedSet(new HashSet());
    public static final svh<Long> c = a("measurement.ad_id_cache_time", 10000L, 10000L, nn2.f);
    public static final svh<Long> d = a("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, u63.V);
    public static final svh<Long> e = a("measurement.config.cache_time", 86400000L, 3600000L, ewa.b0);
    public static final svh<String> f = a("measurement.config.url_scheme", "https", "https", hh1.V);
    public static final svh<String> g = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", jh2.b0);
    public static final svh<Integer> h = a("measurement.upload.max_bundles", 100, 100, ewa.c0);
    public static final svh<Integer> i = a("measurement.upload.max_batch_size", 65536, 65536, wab.d0);
    public static final svh<Integer> j = a("measurement.upload.max_bundle_size", 65536, 65536, u63.Z);
    public static final svh<Integer> k = a("measurement.upload.max_events_per_bundle", 1000, 1000, mh2.i0);
    public static final svh<Integer> l = a("measurement.upload.max_events_per_day", 100000, 100000, ygg.e0);
    public static final svh<Integer> m = a("measurement.upload.max_error_events_per_day", 1000, 1000, ie7.i0);
    public static final svh<Integer> n = a("measurement.upload.max_public_events_per_day", 50000, 50000, ojh.b);
    public static final svh<Integer> o = a("measurement.upload.max_conversions_per_day", 10000, 10000, wab.b0);
    public static final svh<Integer> p = a("measurement.upload.max_realtime_events_per_day", 10, 10, ewa.a0);
    public static final svh<Integer> q = a("measurement.store.max_stored_events_per_app", 100000, 100000, ypd.e0);
    public static final svh<String> r = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", hh2.b0);
    public static final svh<Long> s = a("measurement.upload.backoff_period", 43200000L, 43200000L, cr8.W);

    static {
        a("measurement.upload.window_interval", 3600000L, 3600000L, q92.m0);
        t = a("measurement.upload.interval", 3600000L, 3600000L, u63.W);
        u = a("measurement.upload.realtime_upload_interval", 10000L, 10000L, r03.b0);
        v = a("measurement.upload.debug_upload_interval", 1000L, 1000L, ojh.c);
        w = a("measurement.upload.minimum_delay", 500L, 500L, yid.d);
        x = a("measurement.alarm_manager.minimum_interval", 60000L, 60000L, web.f);
        y = a("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, ygg.b0);
        z = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, ypd.f0);
        A = a("measurement.upload.initial_upload_delay_time", 15000L, 15000L, jh2.a0);
        B = a("measurement.upload.retry_time", 1800000L, 1800000L, c0h.m0);
        C = a("measurement.upload.retry_count", 6, 6, mh2.f0);
        D = a("measurement.upload.max_queue_time", 2419200000L, 2419200000L, ee3.Z);
        E = a("measurement.lifetimevalue.max_currency_tracked", 4, 4, wg2.c0);
        Integer numValueOf = Integer.valueOf(UiRumDebugListener.DEFAULT_ALPHA);
        F = a("measurement.audience.filter_result_max_count", numValueOf, numValueOf, u63.X);
        G = a("measurement.upload.max_public_user_properties", 25, 25, null);
        H = a("measurement.upload.max_event_name_cardinality", 500, 500, null);
        I = a("measurement.upload.max_public_event_params", 25, 25, null);
        J = a("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, q92.n0);
        Boolean bool = Boolean.FALSE;
        K = a("measurement.test.boolean_flag", bool, bool, w74.c0);
        L = a("measurement.test.string_flag", "---", "---", nn2.V);
        M = a("measurement.test.long_flag", -1L, -1L, ie7.j0);
        N = a("measurement.test.int_flag", -2, -2, ojh.d);
        Double dValueOf = Double.valueOf(-3.0d);
        O = a("measurement.test.double_flag", dValueOf, dValueOf, wab.c0);
        P = a("measurement.experiment.max_ids", 50, 50, boa.e0);
        Q = a("measurement.max_bundles_per_iteration", 2, 2, pnb.j0);
        R = a("measurement.validation.internal_limits_internal_event_params", bool, bool, web.V);
        Boolean bool2 = Boolean.TRUE;
        S = a("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", bool2, bool2, pg8.y0);
        T = a("measurement.collection.firebase_global_collection_flag_enabled", bool2, bool2, mh2.g0);
        U = a("measurement.collection.efficient_engagement_reporting_enabled_2", bool2, bool2, ak2.b0);
        V = a("measurement.collection.redundant_engagement_removal_enabled", bool, bool, cr8.X);
        W = a("measurement.client.freeride_engagement_fix", bool2, bool2, ka2.c0);
        X = a("measurement.experiment.enable_experiment_reporting", bool2, bool2, nn2.W);
        a("measurement.collection.log_event_and_bundle_v2", bool2, bool2, u63.Y);
        Y = a("measurement.quality.checksum", bool, bool, null);
        Z = a("measurement.sdk.dynamite.allow_remote_dynamite2", bool, bool, ie7.k0);
        a0 = a("measurement.sdk.collection.validate_param_names_alphabetical", bool2, bool2, w74.d0);
        b0 = a("measurement.collection.event_safelist", bool2, bool2, web.W);
        a("measurement.service.audience.invalidate_config_cache_after_app_unisntall", bool2, bool2, pyd.e0);
        c0 = a("measurement.service.audience.fix_skip_audience_with_failed_filters", bool2, bool2, hh2.c0);
        d0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, ak2.c0);
        e0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, ygg.c0);
        f0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, ka2.d0);
        g0 = a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, mh2.h0);
        h0 = a("measurement.sdk.collection.last_deep_link_referrer2", bool2, bool2, r03.c0);
        i0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, wg2.d0);
        j0 = a("measurement.sdk.collection.last_gclid_from_referrer2", bool, bool, w74.e0);
        k0 = a("measurement.sdk.collection.enable_extend_user_property_size", bool2, bool2, h4.b0);
        l0 = a("measurement.upload.file_lock_state_check", bool, bool, boa.f0);
        m0 = a("measurement.sampling.calculate_bundle_timestamp_before_sampling", bool2, bool2, hh2.d0);
        n0 = a("measurement.ga.ga_app_id", bool, bool, pnb.k0);
        o0 = a("measurement.lifecycle.app_backgrounded_tracking", bool2, bool2, ee3.a0);
        p0 = a("measurement.lifecycle.app_in_background_parameter", bool, bool, ak2.d0);
        q0 = a("measurement.integration.disable_firebase_instance_id", bool, bool, wg2.e0);
        r0 = a("measurement.lifecycle.app_backgrounded_engagement", bool, bool, ka2.e0);
        s0 = a("measurement.collection.service.update_with_analytics_fix", bool, bool, r03.d0);
        t0 = a("measurement.service.use_appinfo_modified", bool, bool, cr8.Y);
        u0 = a("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, nn2.X);
        v0 = a("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, ojh.e);
        w0 = a("measurement.config.string.always_update_disk_on_set", bool2, bool2, w74.f0);
        x0 = a("measurement.scheduler.task_thread.cleanup_on_exit", bool, bool, boa.g0);
        y0 = a("measurement.upload.file_truncate_fix", bool, bool, ie7.l0);
        z0 = a("measurement.engagement_time_main_thread", bool2, bool2, hh2.e0);
        A0 = a("measurement.sdk.referrer.delayed_install_referrer_api", bool, bool, pnb.l0);
        B0 = a("measurement.sdk.screen.disabling_automatic_reporting", bool, bool, pyd.f0);
        C0 = a("measurement.sdk.screen.manual_screen_view_logging", bool, bool, ypd.h0);
        D0 = a("measurement.gold.enhanced_ecommerce.format_logs", bool2, bool2, c0h.n0);
        E0 = a("measurement.gold.enhanced_ecommerce.nested_param_daily_event_count", bool2, bool2, ygg.d0);
        F0 = a("measurement.gold.enhanced_ecommerce.upload_nested_complex_events", bool2, bool2, ak2.e0);
        G0 = a("measurement.gold.enhanced_ecommerce.log_nested_complex_events", bool2, bool2, cr8.Z);
        H0 = a("measurement.gold.enhanced_ecommerce.updated_schema.client", bool2, bool2, wg2.f0);
        I0 = a("measurement.gold.enhanced_ecommerce.updated_schema.service", bool2, bool2, h4.c0);
        a("measurement.collection.synthetic_data_mitigation", bool, bool, u63.a0);
        J0 = a("measurement.service.configurable_service_limits", bool, bool, ie7.m0);
        K0 = a("measurement.client.configurable_service_limits", bool, bool, w74.g0);
        L0 = a("measurement.androidId.delete_feature", bool2, bool2, ypd.i0);
        M0 = a("measurement.client.global_params.dev", bool, bool, zkd.a0);
        N0 = a("measurement.service.global_params", bool, bool, c0h.o0);
        a("measurement.service.global_params_in_payload", bool2, bool2, mh2.j0);
        O0 = a("measurement.client.string_reader", bool2, bool2, jh2.c0);
        P0 = a("measurement.sdk.attribution.cache", bool2, bool2, wg2.g0);
        Q0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, hh1.W);
        R0 = a("measurement.service.database_return_empty_collection", bool2, bool2, cr8.a0);
    }

    @VisibleForTesting
    public static <V> svh<V> a(String str, V v2, V v3, nvh<V> nvhVar) {
        svh<V> svhVar = new svh<>(str, v2, v3, nvhVar);
        a.add(svhVar);
        return svhVar;
    }
}
