package defpackage;

import com.datadog.android.core.internal.CoreFeature;
import com.datadog.android.core.internal.data.upload.DataOkHttpUploader;
import com.datadog.android.log.LogAttributes;
import com.datadog.android.rum.internal.debug.UiRumDebugListener;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import org.webrtc.MediaStreamTrack;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: loaded from: classes3.dex */
public final class fv6 {
    public static final fv6 A0;
    public static final fv6 A1;
    public static final fv6 A2;
    public static final fv6 A3;
    public static final fv6 A4;
    public static final fv6 A5;
    public static final fv6 A6;
    public static final fv6 A7;
    public static final fv6 A8;
    public static final fv6 A9;
    public static final fv6 B0;
    public static final fv6 B1;
    public static final fv6 B2;
    public static final fv6 B3;
    public static final fv6 B4;
    public static final fv6 B5;
    public static final fv6 B6;
    public static final fv6 B7;
    public static final fv6 B8;
    public static final fv6 B9;
    public static final fv6 C0;
    public static final fv6 C1;
    public static final fv6 C2;
    public static final fv6 C3;
    public static final fv6 C4;
    public static final fv6 C5;
    public static final fv6 C6;
    public static final fv6 C7;
    public static final fv6 C8;
    public static final fv6 C9;
    public static final fv6 D0;
    public static final fv6 D1;
    public static final fv6 D2;
    public static final fv6 D3;
    public static final fv6 D4;
    public static final fv6 D5;
    public static final fv6 D6;
    public static final fv6 D7;
    public static final fv6 D8;
    public static final fv6 D9;
    public static final fv6 E0;
    public static final fv6 E1;
    public static final fv6 E2;
    public static final fv6 E3;
    public static final fv6 E4;
    public static final fv6 E5;
    public static final fv6 E6;
    public static final fv6 E7;
    public static final fv6 E8;
    public static final fv6 E9;
    public static final fv6 F0;
    public static final fv6 F1;
    public static final fv6 F2;
    public static final fv6 F3;
    public static final fv6 F4;
    public static final fv6 F5;
    public static final fv6 F6;
    public static final fv6 F7;
    public static final fv6 F8;
    public static final fv6 F9;
    public static final fv6 G0;
    public static final fv6 G1;
    public static final fv6 G2;
    public static final fv6 G3;
    public static final fv6 G4;
    public static final fv6 G5;
    public static final fv6 G6;
    public static final fv6 G7;
    public static final fv6 G8;
    public static final fv6 G9;
    public static final fv6 H0;
    public static final fv6 H1;
    public static final fv6 H2;
    public static final fv6 H3;
    public static final fv6 H4;
    public static final fv6 H5;
    public static final fv6 H6;
    public static final fv6 H7;
    public static final fv6 H8;
    public static final fv6 H9;
    public static final fv6 I0;
    public static final fv6 I1;
    public static final fv6 I2;
    public static final fv6 I3;
    public static final fv6 I4;
    public static final fv6 I5;
    public static final fv6 I6;
    public static final fv6 I7;
    public static final fv6 I8;
    public static final fv6 I9;
    public static final fv6 J0;
    public static final fv6 J1;
    public static final fv6 J2;
    public static final fv6 J3;
    public static final fv6 J4;
    public static final fv6 J5;
    public static final fv6 J6;
    public static final fv6 J7;
    public static final fv6 J8;
    public static final fv6 J9;
    public static final fv6 K0;
    public static final fv6 K1;
    public static final fv6 K2;
    public static final fv6 K3;
    public static final fv6 K4;
    public static final fv6 K5;
    public static final fv6 K6;
    public static final fv6 K7;
    public static final fv6 K8;
    public static final fv6 K9;
    public static final fv6 L0;
    public static final fv6 L1;
    public static final fv6 L2;
    public static final fv6 L3;
    public static final fv6 L4;
    public static final fv6 L5;
    public static final fv6 L6;
    public static final fv6 L7;
    public static final fv6 L8;
    public static final fv6 L9;
    public static final fv6 M0;
    public static final fv6 M1;
    public static final fv6 M2;
    public static final fv6 M3;
    public static final fv6 M4;
    public static final fv6 M5;
    public static final fv6 M6;
    public static final fv6 M7;
    public static final fv6 M8;
    public static final fv6 M9;
    public static final fv6 N0;
    public static final fv6 N1;
    public static final fv6 N2;
    public static final fv6 N3;
    public static final fv6 N4;
    public static final fv6 N5;
    public static final fv6 N6;
    public static final fv6 N7;
    public static final fv6 N8;
    public static final fv6 N9;
    public static final fv6 O0;
    public static final fv6 O1;
    public static final fv6 O2;
    public static final fv6 O3;
    public static final fv6 O4;
    public static final fv6 O5;
    public static final fv6 O6;
    public static final fv6 O7;
    public static final fv6 O8;
    public static final fv6 O9;
    public static final fv6 P0;
    public static final fv6 P1;
    public static final fv6 P2;
    public static final fv6 P3;
    public static final fv6 P4;
    public static final fv6 P5;
    public static final fv6 P6;
    public static final fv6 P7;
    public static final fv6 P8;
    public static final fv6 P9;
    public static final fv6 Q0;
    public static final fv6 Q1;
    public static final fv6 Q2;
    public static final fv6 Q3;
    public static final fv6 Q4;
    public static final fv6 Q5;
    public static final fv6 Q6;
    public static final fv6 Q7;
    public static final fv6 Q8;
    public static final fv6 Q9;
    public static final fv6 R0;
    public static final fv6 R1;
    public static final fv6 R2;
    public static final fv6 R3;
    public static final fv6 R4;
    public static final fv6 R5;
    public static final fv6 R6;
    public static final fv6 R7;
    public static final fv6 R8;
    public static final fv6 R9;
    public static final fv6 S0;
    public static final fv6 S1;
    public static final fv6 S2;
    public static final fv6 S3;
    public static final fv6 S4;
    public static final fv6 S5;
    public static final fv6 S6;
    public static final fv6 S7;
    public static final fv6 S8;
    public static final fv6 S9;
    public static final fv6 T0;
    public static final fv6 T1;
    public static final fv6 T2;
    public static final fv6 T3;
    public static final fv6 T4;
    public static final fv6 T5;
    public static final fv6 T6;
    public static final fv6 T7;
    public static final fv6 T8;
    public static final fv6 T9;
    public static final fv6 U0;
    public static final fv6 U1;
    public static final fv6 U2;
    public static final fv6 U3;
    public static final fv6 U4;
    public static final fv6 U5;
    public static final fv6 U6;
    public static final fv6 U7;
    public static final fv6 U8;
    public static final fv6 U9;
    public static final fv6 V;
    public static final fv6 V0;
    public static final fv6 V1;
    public static final fv6 V2;
    public static final fv6 V3;
    public static final fv6 V4;
    public static final fv6 V5;
    public static final fv6 V6;
    public static final fv6 V7;
    public static final fv6 V8;
    public static final fv6 V9;
    public static final fv6 W;
    public static final fv6 W0;
    public static final fv6 W1;
    public static final fv6 W2;
    public static final fv6 W3;
    public static final fv6 W4;
    public static final fv6 W5;
    public static final fv6 W6;
    public static final fv6 W7;
    public static final fv6 W8;
    public static final fv6 W9;
    public static final fv6 X;
    public static final fv6 X0;
    public static final fv6 X1;
    public static final fv6 X2;
    public static final fv6 X3;
    public static final fv6 X4;
    public static final fv6 X5;
    public static final fv6 X6;
    public static final fv6 X7;
    public static final fv6 X8;
    public static final fv6 X9;
    public static final fv6 Y;
    public static final fv6 Y0;
    public static final fv6 Y1;
    public static final fv6 Y2;
    public static final fv6 Y3;
    public static final fv6 Y4;
    public static final fv6 Y5;
    public static final fv6 Y6;
    public static final fv6 Y7;
    public static final fv6 Y8;
    public static final fv6 Y9;
    public static final fv6 Z;
    public static final fv6 Z0;
    public static final fv6 Z1;
    public static final fv6 Z2;
    public static final fv6 Z3;
    public static final fv6 Z4;
    public static final fv6 Z5;
    public static final fv6 Z6;
    public static final fv6 Z7;
    public static final fv6 Z8;
    public static final fv6 Z9;
    public static final fv6 a;
    public static final fv6 a0;
    public static final fv6 a1;
    public static final fv6 a2;
    public static final fv6 a3;
    public static final fv6 a4;
    public static final fv6 a5;
    public static final fv6 a6;
    public static final fv6 a7;
    public static final fv6 a8;
    public static final fv6 a9;
    public static final fv6 aa;
    public static final fv6 b;
    public static final fv6 b0;
    public static final fv6 b1;
    public static final fv6 b2;
    public static final fv6 b3;
    public static final fv6 b4;
    public static final fv6 b5;
    public static final fv6 b6;
    public static final fv6 b7;
    public static final fv6 b8;
    public static final fv6 b9;
    public static final fv6 ba;
    public static final fv6 c;
    public static final fv6 c0;
    public static final fv6 c1;
    public static final fv6 c2;
    public static final fv6 c3;
    public static final fv6 c4;
    public static final fv6 c5;
    public static final fv6 c6;
    public static final fv6 c7;
    public static final fv6 c8;
    public static final fv6 c9;
    public static final fv6 ca;
    public static final fv6 d;
    public static final fv6 d0;
    public static final fv6 d1;
    public static final fv6 d2;
    public static final fv6 d3;
    public static final fv6 d4;
    public static final fv6 d5;
    public static final fv6 d6;
    public static final fv6 d7;
    public static final fv6 d8;
    public static final fv6 d9;
    public static final fv6 da;
    public static final fv6 e;
    public static final fv6 e0;
    public static final fv6 e1;
    public static final fv6 e2;
    public static final fv6 e3;
    public static final fv6 e4;
    public static final fv6 e5;
    public static final fv6 e6;
    public static final fv6 e7;
    public static final fv6 e8;
    public static final fv6 e9;
    public static final fv6 ea;
    public static final fv6 f;
    public static final fv6 f0;
    public static final fv6 f1;
    public static final fv6 f2;
    public static final fv6 f3;
    public static final fv6 f4;
    public static final fv6 f5;
    public static final fv6 f6;
    public static final fv6 f7;
    public static final fv6 f8;
    public static final fv6 f9;
    public static final fv6 fa;
    public static final fv6 g0;
    public static final fv6 g1;
    public static final fv6 g2;
    public static final fv6 g3;
    public static final fv6 g4;
    public static final fv6 g5;
    public static final fv6 g6;
    public static final fv6 g7;
    public static final fv6 g8;
    public static final fv6 g9;
    public static final fv6 ga;
    public static final fv6 h0;
    public static final fv6 h1;
    public static final fv6 h2;
    public static final fv6 h3;
    public static final fv6 h4;
    public static final fv6 h5;
    public static final fv6 h6;
    public static final fv6 h7;
    public static final fv6 h8;
    public static final fv6 h9;
    public static final fv6 ha;
    public static final fv6 i0;
    public static final fv6 i1;
    public static final fv6 i2;
    public static final fv6 i3;
    public static final fv6 i4;
    public static final fv6 i5;
    public static final fv6 i6;
    public static final fv6 i7;
    public static final fv6 i8;
    public static final fv6 i9;
    public static final fv6 ia;
    public static final fv6 j0;
    public static final fv6 j1;
    public static final fv6 j2;
    public static final fv6 j3;
    public static final fv6 j4;
    public static final fv6 j5;
    public static final fv6 j6;
    public static final fv6 j7;
    public static final fv6 j8;
    public static final fv6 j9;
    public static final fv6 ja;
    public static final fv6 k0;
    public static final fv6 k1;
    public static final fv6 k2;
    public static final fv6 k3;
    public static final fv6 k4;
    public static final fv6 k5;
    public static final fv6 k6;
    public static final fv6 k7;
    public static final fv6 k8;
    public static final fv6 k9;
    public static final fv6 ka;
    public static final fv6 l0;
    public static final fv6 l1;
    public static final fv6 l2;
    public static final fv6 l3;
    public static final fv6 l4;
    public static final fv6 l5;
    public static final fv6 l6;
    public static final fv6 l7;
    public static final fv6 l8;
    public static final fv6 l9;
    public static final fv6 la;
    public static final fv6 m0;
    public static final fv6 m1;
    public static final fv6 m2;
    public static final fv6 m3;
    public static final fv6 m4;
    public static final fv6 m5;
    public static final fv6 m6;
    public static final fv6 m7;
    public static final fv6 m8;
    public static final fv6 m9;
    public static final fv6 ma;
    public static final fv6 n0;
    public static final fv6 n1;
    public static final fv6 n2;
    public static final fv6 n3;
    public static final fv6 n4;
    public static final fv6 n5;
    public static final fv6 n6;
    public static final fv6 n7;
    public static final fv6 n8;
    public static final fv6 n9;
    public static final fv6 na;
    public static final fv6 o0;
    public static final fv6 o1;
    public static final fv6 o2;
    public static final fv6 o3;
    public static final fv6 o4;
    public static final fv6 o5;
    public static final fv6 o6;
    public static final fv6 o7;
    public static final fv6 o8;
    public static final fv6 o9;
    public static final fv6 oa;
    public static final fv6 p0;
    public static final fv6 p1;
    public static final fv6 p2;
    public static final fv6 p3;
    public static final fv6 p4;
    public static final fv6 p5;
    public static final fv6 p6;
    public static final fv6 p7;
    public static final fv6 p8;
    public static final fv6 p9;
    public static final fv6 pa;
    public static final fv6 q0;
    public static final fv6 q1;
    public static final fv6 q2;
    public static final fv6 q3;
    public static final fv6 q4;
    public static final fv6 q5;
    public static final fv6 q6;
    public static final fv6 q7;
    public static final fv6 q8;
    public static final fv6 q9;
    public static final fv6 qa;
    public static final fv6 r0;
    public static final fv6 r1;
    public static final fv6 r2;
    public static final fv6 r3;
    public static final fv6 r4;
    public static final fv6 r5;
    public static final fv6 r6;
    public static final fv6 r7;
    public static final fv6 r8;
    public static final fv6 r9;
    public static final fv6 ra;
    public static final fv6 s0;
    public static final fv6 s1;
    public static final fv6 s2;
    public static final fv6 s3;
    public static final fv6 s4;
    public static final fv6 s5;
    public static final fv6 s6;
    public static final fv6 s7;
    public static final fv6 s8;
    public static final fv6 s9;
    public static final fv6 sa;
    public static final fv6 t0;
    public static final fv6 t1;
    public static final fv6 t2;
    public static final fv6 t3;
    public static final fv6 t4;
    public static final fv6 t5;
    public static final fv6 t6;
    public static final fv6 t7;
    public static final fv6 t8;
    public static final fv6 t9;
    public static final fv6 ta;
    public static final fv6 u0;
    public static final fv6 u1;
    public static final fv6 u2;
    public static final fv6 u3;
    public static final fv6 u4;
    public static final fv6 u5;
    public static final fv6 u6;
    public static final fv6 u7;
    public static final fv6 u8;
    public static final fv6 u9;
    public static final fv6 ua;
    public static final fv6 v0;
    public static final fv6 v1;
    public static final fv6 v2;
    public static final fv6 v3;
    public static final fv6 v4;
    public static final fv6 v5;
    public static final fv6 v6;
    public static final fv6 v7;
    public static final fv6 v8;
    public static final fv6 v9;
    public static final fv6 va;
    public static final fv6 w0;
    public static final fv6 w1;
    public static final fv6 w2;
    public static final fv6 w3;
    public static final fv6 w4;
    public static final fv6 w5;
    public static final fv6 w6;
    public static final fv6 w7;
    public static final fv6 w8;
    public static final fv6 w9;
    public static final /* synthetic */ fv6[] wa;
    public static final fv6 x0;
    public static final fv6 x1;
    public static final fv6 x2;
    public static final fv6 x3;
    public static final fv6 x4;
    public static final fv6 x5;
    public static final fv6 x6;
    public static final fv6 x7;
    public static final fv6 x8;
    public static final fv6 x9;
    public static final /* synthetic */ wv4 xa;
    public static final fv6 y0;
    public static final fv6 y1;
    public static final fv6 y2;
    public static final fv6 y3;
    public static final fv6 y4;
    public static final fv6 y5;
    public static final fv6 y6;
    public static final fv6 y7;
    public static final fv6 y8;
    public static final fv6 y9;
    public static final fv6 z0;
    public static final fv6 z1;
    public static final fv6 z2;
    public static final fv6 z3;
    public static final fv6 z4;
    public static final fv6 z5;
    public static final fv6 z6;
    public static final fv6 z7;
    public static final fv6 z8;
    public static final fv6 z9;
    private final String rawValue;
    private final ar6 variant;

    static {
        ar6 ar6Var = ar6.Filled;
        a = new fv6("Accessibility", 0, "accessibility", ar6Var);
        ar6 ar6Var2 = ar6.Stroke;
        b = new fv6("AccessibilityStroke", 1, "accessibility", ar6Var2);
        c = new fv6("AccountingLicense", 2, "accountinglicense", ar6Var);
        d = new fv6("AccountingLicenseStroke", 3, "accountinglicense", ar6Var2);
        e = new fv6("AdditionalInfo", 4, "additionalinfo", ar6Var);
        f = new fv6("AdditionalInfoStroke", 5, "additionalinfo", ar6Var2);
        V = new fv6("AdditionalOptions", 6, "additionaloptions", ar6Var);
        W = new fv6("AdditionalOptionsStroke", 7, "additionaloptions", ar6Var2);
        X = new fv6("AiGeneral", 8, "aigeneral", ar6Var);
        Y = new fv6("AiGeneralStroke", 9, "aigeneral", ar6Var2);
        Z = new fv6("AiLogo", 10, "ailogo", ar6Var);
        a0 = new fv6("AiLogoStroke", 11, "ailogonew", ar6Var2);
        b0 = new fv6("AiLogoFilled", 12, "ailogonew", ar6Var);
        c0 = new fv6("AddPerson", 13, "addperson", ar6Var);
        d0 = new fv6("AddPersonStroke", 14, "addperson", ar6Var2);
        e0 = new fv6("AddToFolder", 15, "addtofolder", ar6Var);
        f0 = new fv6("AddToFolderStroke", 16, "addtofolder", ar6Var2);
        g0 = new fv6("Android", 17, CoreFeature.DEFAULT_SOURCE_NAME, ar6Var);
        h0 = new fv6("AndroidStroke", 18, CoreFeature.DEFAULT_SOURCE_NAME, ar6Var2);
        i0 = new fv6("Apple", 19, "apple", ar6Var);
        j0 = new fv6("AppleStroke", 20, "apple", ar6Var2);
        k0 = new fv6("Archive", 21, "archive", ar6Var);
        l0 = new fv6("ArchiveStroke", 22, "archive", ar6Var2);
        m0 = new fv6("ArrowDown", 23, "arrowdown", ar6Var);
        n0 = new fv6("ArrowDownStroke", 24, "arrowdown", ar6Var2);
        o0 = new fv6("ArrowLeft", 25, "arrowleft", ar6Var);
        p0 = new fv6("ArrowLeftStroke", 26, "arrowleft", ar6Var2);
        q0 = new fv6("ArrowRight", 27, "arrowright", ar6Var);
        r0 = new fv6("ArrowRightStroke", 28, "arrowright", ar6Var2);
        s0 = new fv6("ArrowUp", 29, "arrowup", ar6Var);
        t0 = new fv6("ArrowUpStroke", 30, "arrowup", ar6Var2);
        u0 = new fv6("ArtificialIntelligence", 31, "artificialintelligence", ar6Var);
        v0 = new fv6("ArtificialIntelligenceStroke", 32, "artificialintelligence", ar6Var2);
        w0 = new fv6("Assessments", 33, "assessments", ar6Var);
        x0 = new fv6("AssessmentsStroke", 34, "assessments", ar6Var2);
        y0 = new fv6("Attachment", 35, "attachment", ar6Var);
        z0 = new fv6("AttachmentStroke", 36, "attachment", ar6Var2);
        A0 = new fv6("Award", 37, "award", ar6Var);
        B0 = new fv6("AwardStroke", 38, "award", ar6Var2);
        C0 = new fv6("Ban", 39, "ban", ar6Var);
        D0 = new fv6("BanStroke", 40, "ban", ar6Var2);
        E0 = new fv6("BankAccount", 41, "bankaccount", ar6Var);
        F0 = new fv6("BankAccountStroke", 42, "bankaccount", ar6Var2);
        G0 = new fv6("Benefits", 43, "benefits", ar6Var);
        H0 = new fv6("BenefitsStroke", 44, "benefits", ar6Var2);
        I0 = new fv6("BenefitsHealthInsurance", 45, "benefitshealthinsurance", ar6Var);
        J0 = new fv6("BenefitsHealthInsuranceStroke", 46, "benefitshealthinsurance", ar6Var2);
        K0 = new fv6("BenefitsInternetRupee", 47, "benefitsinternetrupee", ar6Var);
        L0 = new fv6("BenefitsInternetRupeeStroke", 48, "benefitsinternetrupee", ar6Var2);
        M0 = new fv6("BenefitsLeaveRupee", 49, "benefitsleaverupee", ar6Var);
        N0 = new fv6("BenefitsLeaveRupeeStroke", 50, "benefitsleaverupee", ar6Var2);
        O0 = new fv6("BenefitsLifeInsurance", 51, "benefitslifeinsurance", ar6Var);
        P0 = new fv6("BenefitsLifeInsuranceStroke", 52, "benefitslifeinsurance", ar6Var2);
        Q0 = new fv6("BenefitsMealRupee", 53, "benefitsmealrupee", ar6Var);
        R0 = new fv6("BenefitsMealRupeeStroke", 54, "benefitsmealrupee", ar6Var2);
        S0 = new fv6("BenefitsMobileRupee", 55, "benefitsmobilerupee", ar6Var);
        T0 = new fv6("BenefitsMobileRupeeStroke", 56, "benefitsmobilerupee", ar6Var2);
        U0 = new fv6("BenefitsProvidentFundRupee", 57, "benefitsprovidentfundrupee", ar6Var);
        V0 = new fv6("BenefitsProvidentFundRupeeStroke", 58, "benefitsprovidentfundrupee", ar6Var2);
        W0 = new fv6("BenefitsPtoSickLeaveRupee", 59, "benefitsptosickleaverupee", ar6Var);
        X0 = new fv6("BenefitsPtoSickLeaveRupeeStroke", 60, "benefitsptosickleaverupee", ar6Var2);
        Y0 = new fv6("Bike", 61, "bike", ar6Var);
        Z0 = new fv6("BikeStroke", 62, "bike", ar6Var2);
        a1 = new fv6("Bold", 63, "bold", ar6Var);
        b1 = new fv6("BoldStroke", 64, "bold", ar6Var2);
        c1 = new fv6("Bookmark", 65, "bookmark", ar6Var);
        d1 = new fv6("BookmarkStroke", 66, "bookmark", ar6Var2);
        e1 = new fv6("BulletedList", 67, "bulletedlist", ar6Var);
        f1 = new fv6("BulletedListStroke", 68, "bulletedlist", ar6Var2);
        g1 = new fv6("Calendar", 69, "calendar", ar6Var);
        h1 = new fv6("CalendarStroke", 70, "calendar", ar6Var2);
        i1 = new fv6("Camera", 71, "camera", ar6Var);
        j1 = new fv6("CameraStroke", 72, "camera", ar6Var2);
        k1 = new fv6("Campaign", 73, "campaign", ar6Var);
        l1 = new fv6("CampaignStroke", 74, "campaign", ar6Var2);
        m1 = new fv6("CandidateMatch", 75, "candidatematch", ar6Var);
        n1 = new fv6("CandidateMatchStroke", 76, "candidatematch", ar6Var2);
        o1 = new fv6("Car", 77, "car", ar6Var);
        p1 = new fv6("CarStroke", 78, "car", ar6Var2);
        q1 = new fv6("CaretDown", 79, "caretdown", ar6Var);
        r1 = new fv6("CaretDownStroke", 80, "caretdown", ar6Var2);
        s1 = new fv6("CaretDual", 81, "caretdual", ar6Var);
        t1 = new fv6("CaretDualStroke", 82, "caretdual", ar6Var2);
        u1 = new fv6("CaretUp", 83, "caretup", ar6Var);
        v1 = new fv6("CaretUpStroke", 84, "caretup", ar6Var2);
        w1 = new fv6("Certification", 85, "certification", ar6Var);
        x1 = new fv6("CertificationStroke", 86, "certification", ar6Var2);
        y1 = new fv6("Chat", 87, "chat", ar6Var);
        z1 = new fv6("ChatStroke", 88, "chat", ar6Var2);
        A1 = new fv6("Check", 89, "check", ar6Var);
        B1 = new fv6("CheckStroke", 90, "check", ar6Var2);
        C1 = new fv6("CheckCircle", 91, "checkcircle", ar6Var);
        D1 = new fv6("CheckCircleStroke", 92, "checkcircle", ar6Var2);
        E1 = new fv6("ChevronDown", 93, "chevrondown", ar6Var);
        F1 = new fv6("ChevronDownStroke", 94, "chevrondown", ar6Var2);
        G1 = new fv6("ChevronLeft", 95, "chevronleft", ar6Var);
        H1 = new fv6("ChevronLeftStroke", 96, "chevronleft", ar6Var2);
        I1 = new fv6("ChevronRight", 97, "chevronright", ar6Var);
        J1 = new fv6("ChevronRightStroke", 98, "chevronright", ar6Var2);
        K1 = new fv6("ChevronUp", 99, "chevronup", ar6Var);
        L1 = new fv6("ChevronUpStroke", 100, "chevronup", ar6Var2);
        M1 = new fv6("Click", 101, "click", ar6Var);
        N1 = new fv6("ClickStroke", 102, "click", ar6Var2);
        O1 = new fv6("Clipboard", 103, "clipboard", ar6Var);
        P1 = new fv6("ClipboardStroke", 104, "clipboard", ar6Var2);
        Q1 = new fv6("Clock", 105, "clock", ar6Var);
        R1 = new fv6("ClockStroke", 106, "clock", ar6Var2);
        S1 = new fv6("ClockDashed", 107, "clockdashed", ar6Var);
        T1 = new fv6("ClockDashedStroke", 108, "clockdashed", ar6Var2);
        U1 = new fv6("ClockHalfDashed", 109, "clockhalfdashed", ar6Var);
        V1 = new fv6("ClockHalfDashedStroke", 110, "clockhalfdashed", ar6Var2);
        W1 = new fv6("Close", 111, "close", ar6Var);
        X1 = new fv6("CloseStroke", 112, "close", ar6Var2);
        Y1 = new fv6("CloseCircle", 113, "closecircle", ar6Var);
        Z1 = new fv6("CloseCircleStroke", 114, "closecircle", ar6Var2);
        a2 = new fv6("Code", 115, "code", ar6Var);
        b2 = new fv6("CodeStroke", 116, "code", ar6Var2);
        c2 = new fv6("Collapse", 117, "collapse", ar6Var);
        d2 = new fv6("CollapseStroke", 118, "collapse", ar6Var2);
        e2 = new fv6("Commute", 119, "commute", ar6Var);
        f2 = new fv6("CommuteStroke", 120, "commute", ar6Var2);
        g2 = new fv6("Company", 121, "company", ar6Var);
        h2 = new fv6("CompanyStroke", 122, "company", ar6Var2);
        i2 = new fv6("Comparison", 123, "comparison", ar6Var);
        j2 = new fv6("ComparisonStroke", 124, "comparison", ar6Var2);
        k2 = new fv6("ConvertToEditable", 125, "converttoeditable", ar6Var);
        l2 = new fv6("ConvertToEditableStroke", 126, "converttoeditable", ar6Var2);
        m2 = new fv6("Copy", 127, "copy", ar6Var);
        n2 = new fv6("CopyStroke", IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT, "copy", ar6Var2);
        o2 = new fv6("CreditCard", 129, "creditcard", ar6Var);
        p2 = new fv6("CreditCardStroke", 130, "creditcard", ar6Var2);
        q2 = new fv6("CurrentLocation", 131, "currentlocation", ar6Var);
        r2 = new fv6("CurrentLocationStroke", 132, "currentlocation", ar6Var2);
        s2 = new fv6("Dataset", 133, "dataset", ar6Var);
        t2 = new fv6("DatasetStroke", 134, "dataset", ar6Var2);
        u2 = new fv6("DataTable", 135, "datatable", ar6Var);
        v2 = new fv6("DataTableStroke", 136, "datatable", ar6Var2);
        w2 = new fv6("Database", 137, "database", ar6Var);
        x2 = new fv6("DatabaseStroke", 138, "database", ar6Var2);
        y2 = new fv6("DataBar", 139, "databar", ar6Var);
        z2 = new fv6("DataBarStroke", 140, "databar", ar6Var2);
        A2 = new fv6("DataLineDown", 141, "datalinedown", ar6Var);
        B2 = new fv6("DataLineDownStroke", 142, "datalinedown", ar6Var2);
        C2 = new fv6("DataLineFlat", 143, "datalineflat", ar6Var);
        D2 = new fv6("DataLineFlatStroke", 144, "datalineflat", ar6Var2);
        E2 = new fv6("DataLineUp", 145, "datalineup", ar6Var);
        F2 = new fv6("DataLineUpStroke", 146, "datalineup", ar6Var2);
        G2 = new fv6("Date", 147, LogAttributes.DATE, ar6Var);
        H2 = new fv6("DateStroke", 148, LogAttributes.DATE, ar6Var2);
        I2 = new fv6("DateApproved", 149, "dateapproved", ar6Var);
        J2 = new fv6("DateApprovedStroke", 150, "dateapproved", ar6Var2);
        K2 = new fv6("DateCanceled", 151, "datecanceled", ar6Var);
        L2 = new fv6("DateCanceledStroke", 152, "datecanceled", ar6Var2);
        M2 = new fv6("DateScheduled", 153, "datescheduled", ar6Var);
        N2 = new fv6("DateScheduledStroke", 154, "datescheduled", ar6Var2);
        O2 = new fv6("Desktop", 155, "desktop", ar6Var);
        P2 = new fv6("DesktopStroke", 156, "desktop", ar6Var2);
        Q2 = new fv6("DesktopReport", 157, "desktopreport", ar6Var);
        R2 = new fv6("DesktopReportStroke", 158, "desktopreport", ar6Var2);
        S2 = new fv6("Discover", 159, "discover", ar6Var);
        T2 = new fv6("DiscoverStroke", 160, "discover", ar6Var2);
        U2 = new fv6("DocReview", 161, "docreview", ar6Var);
        V2 = new fv6("DocReviewStroke", 162, "docreview", ar6Var2);
        W2 = new fv6("DoubleChevronLeft", 163, "doublechevronleft", ar6Var);
        X2 = new fv6("DoubleChevronLeftStroke", 164, "doublechevronleft", ar6Var2);
        Y2 = new fv6("DoubleChevronRight", 165, "doublechevronright", ar6Var);
        Z2 = new fv6("DoubleChevronRightStroke", 166, "doublechevronright", ar6Var2);
        a3 = new fv6("Download", 167, "download", ar6Var);
        b3 = new fv6("DownloadStroke", 168, "download", ar6Var2);
        c3 = new fv6("DownloadResume", 169, "downloadresume", ar6Var);
        d3 = new fv6("DownloadResumeStroke", 170, "downloadresume", ar6Var2);
        e3 = new fv6("DriversLicense", 171, "driverslicense", ar6Var);
        f3 = new fv6("DriversLicenseStroke", 172, "driverslicense", ar6Var2);
        g3 = new fv6("Edit", 173, "edit", ar6Var);
        h3 = new fv6("EditStroke", 174, "edit", ar6Var2);
        i3 = new fv6("EditSection", 175, "editsection", ar6Var);
        j3 = new fv6("EditSectionStroke", 176, "editsection", ar6Var2);
        k3 = new fv6("Education", 177, "education", ar6Var);
        l3 = new fv6("EducationStroke", 178, "education", ar6Var2);
        m3 = new fv6("Effects", 179, "effects", ar6Var);
        n3 = new fv6("EffectsStroke", 180, "effects", ar6Var2);
        o3 = new fv6("Error", 181, "error", ar6Var);
        p3 = new fv6("ErrorStroke", 182, "error", ar6Var2);
        q3 = new fv6("Expand", 183, "expand", ar6Var);
        r3 = new fv6("ExpandStroke", 184, "expand", ar6Var2);
        s3 = new fv6("Facebook", 185, "facebook", ar6Var);
        t3 = new fv6("FacebookStroke", 186, "facebook", ar6Var2);
        u3 = new fv6("Figma", 187, "figma", ar6Var);
        v3 = new fv6("FigmaStroke", 188, "figma", ar6Var2);
        w3 = new fv6("FigmaComponent", 189, "figmacomponent", ar6Var);
        x3 = new fv6("FigmaComponentStroke", 190, "figmacomponent", ar6Var2);
        y3 = new fv6("FileCSV", 191, "filecsv", ar6Var);
        z3 = new fv6("FileCSVStroke", 192, "filecsv", ar6Var2);
        A3 = new fv6("FileDoc", 193, "filedoc", ar6Var);
        B3 = new fv6("FileDocStroke", 194, "filedoc", ar6Var2);
        C3 = new fv6("FileImage", 195, "fileimage", ar6Var);
        D3 = new fv6("FileImageStroke", 196, "fileimage", ar6Var2);
        E3 = new fv6("FileMisc", 197, "filemisc", ar6Var);
        F3 = new fv6("FileMiscStroke", 198, "filemisc", ar6Var2);
        G3 = new fv6("FilePreview", 199, "filepreview", ar6Var);
        H3 = new fv6("FilePreviewStroke", UiRumDebugListener.DEFAULT_ALPHA, "filepreview", ar6Var2);
        I3 = new fv6("Filter", 201, "filter", ar6Var);
        J3 = new fv6("FilterStroke", DataOkHttpUploader.HTTP_ACCEPTED, "filter", ar6Var2);
        K3 = new fv6("FormatIndentDecrease", 203, "formatindentdecrease", ar6Var);
        L3 = new fv6("FormatIndentDecreaseStroke", 204, "formatindentdecrease", ar6Var2);
        M3 = new fv6("FormatIndentIncrease", 205, "formatindentincrease", ar6Var);
        N3 = new fv6("FormatIndentIncreaseStroke", 206, "formatindentincrease", ar6Var2);
        O3 = new fv6("Folder", 207, "folder", ar6Var);
        P3 = new fv6("FolderStroke", 208, "folder", ar6Var2);
        Q3 = new fv6("GetDirections", 209, "getdirections", ar6Var);
        R3 = new fv6("GetDirectionsStroke", 210, "getdirections", ar6Var2);
        S3 = new fv6("GitLab", 211, "gitlab", ar6Var);
        T3 = new fv6("GitLabStroke", 212, "gitlab", ar6Var2);
        U3 = new fv6("Guarantee", 213, "guarantee", ar6Var);
        V3 = new fv6("GuaranteeStroke", 214, "guarantee", ar6Var2);
        W3 = new fv6("Hamburger", 215, "hamburger", ar6Var);
        X3 = new fv6("HamburgerStroke", 216, "hamburger", ar6Var2);
        Y3 = new fv6("Healthcare", 217, "healthcare", ar6Var);
        Z3 = new fv6("HealthcareStroke", 218, "healthcare", ar6Var2);
        a4 = new fv6("Hybrid", 219, "hybrid", ar6Var);
        b4 = new fv6("HybridStroke", 220, "hybrid", ar6Var2);
        c4 = new fv6("Heart", 221, "heart", ar6Var);
        d4 = new fv6("HeartStroke", 222, "heart", ar6Var2);
        e4 = new fv6("Hide", 223, "hide", ar6Var);
        f4 = new fv6("HideStroke", 224, "hide", ar6Var2);
        g4 = new fv6("HiringBadge", 225, "hiringbadge", ar6Var);
        h4 = new fv6("HiringBadgeStroke", 226, "hiringbadge", ar6Var2);
        i4 = new fv6("Home", 227, "home", ar6Var);
        j4 = new fv6("HomeStroke", 228, "home", ar6Var2);
        k4 = new fv6("HomeInterview", 229, "homeinterview", ar6Var);
        l4 = new fv6("HomeInterviewStroke", 230, "homeinterview", ar6Var2);
        m4 = new fv6("Hourglass", 231, "hourglass", ar6Var);
        n4 = new fv6("HourglassStroke", 232, "hourglass", ar6Var2);
        o4 = new fv6("HumanSupportAgent", 233, "humansupportagent", ar6Var);
        p4 = new fv6("HumanSupportAgentStroke", 234, "humansupportagent", ar6Var2);
        q4 = new fv6("Information", 235, "information", ar6Var);
        r4 = new fv6("InformationStroke", 236, "information", ar6Var2);
        s4 = new fv6("InsertArrow", 237, "insertarrow", ar6Var);
        t4 = new fv6("InsertArrowStroke", 238, "insertarrow", ar6Var2);
        u4 = new fv6("InsertChatTemplate", 239, "insertchattemplate", ar6Var);
        v4 = new fv6("InsertChatTemplateStroke", 240, "insertchattemplate", ar6Var2);
        w4 = new fv6("InsertTextTemplate", 241, "inserttexttemplate", ar6Var);
        x4 = new fv6("InsertTextTemplateStroke", 242, "inserttexttemplate", ar6Var2);
        y4 = new fv6("InsertVariable", 243, "insertvariable", ar6Var);
        z4 = new fv6("InsertVariableStroke", 244, "insertvariable", ar6Var2);
        A4 = new fv6("Instagram", 245, "instagram", ar6Var);
        B4 = new fv6("InstagramStroke", 246, "instagram", ar6Var2);
        C4 = new fv6("Interview", 247, "interview", ar6Var);
        D4 = new fv6("InterviewStroke", 248, "interview", ar6Var2);
        E4 = new fv6("Italics", 249, "italics", ar6Var);
        F4 = new fv6("ItalicsStroke", 250, "italics", ar6Var2);
        G4 = new fv6("JobPreference", 251, "jobpreference", ar6Var);
        H4 = new fv6("JobPreferenceStroke", 252, "jobpreference", ar6Var2);
        I4 = new fv6("Jobs", 253, "jobs", ar6Var);
        J4 = new fv6("JobsStroke", 254, "jobs", ar6Var2);
        K4 = new fv6("JobTag", 255, "jobtag", ar6Var);
        L4 = new fv6("JobTagStroke", IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER, "jobtag", ar6Var2);
        M4 = new fv6("Keyboard", 257, "keyboard", ar6Var);
        N4 = new fv6("KeyboardStroke", 258, "keyboard", ar6Var2);
        O4 = new fv6("Language", 259, "language", ar6Var);
        P4 = new fv6("LanguageStroke", 260, "language", ar6Var2);
        Q4 = new fv6("Line", 261, "line", ar6Var);
        R4 = new fv6("LineStroke", 262, "line", ar6Var2);
        S4 = new fv6("Link", 263, "link", ar6Var);
        T4 = new fv6("LinkStroke", 264, "link", ar6Var2);
        U4 = new fv6("LinkedIn", 265, "linkedin", ar6Var);
        V4 = new fv6("LinkedInStroke", 266, "linkedin", ar6Var2);
        W4 = new fv6("LinkNone", 267, "linknone", ar6Var);
        X4 = new fv6("LinkNoneStroke", 268, "linknone", ar6Var2);
        Y4 = new fv6("Location", 269, "location", ar6Var);
        Z4 = new fv6("LocationStroke", 270, "location", ar6Var2);
        a5 = new fv6("Lock", 271, "lock", ar6Var);
        b5 = new fv6("LockStroke", 272, "lock", ar6Var2);
        c5 = new fv6("Mail", 273, "mail", ar6Var);
        d5 = new fv6("MailStroke", 274, "mail", ar6Var2);
        e5 = new fv6("MailOpen", 275, "mailopen", ar6Var);
        f5 = new fv6("MailOpenStroke", 276, "mailopen", ar6Var2);
        g5 = new fv6("MailUnread", 277, "mailunread", ar6Var);
        h5 = new fv6("MailUnreadStroke", 278, "mailunread", ar6Var2);
        i5 = new fv6("Maximize", 279, "maximize", ar6Var);
        j5 = new fv6("MaximizeStroke", 280, "maximize", ar6Var2);
        k5 = new fv6("Meal", 281, "meal", ar6Var);
        l5 = new fv6("MealStroke", 282, "meal", ar6Var2);
        m5 = new fv6("Mic", 283, "mic", ar6Var);
        n5 = new fv6("MicStroke", 284, "mic", ar6Var2);
        o5 = new fv6("MicMuted", 285, "micmuted", ar6Var);
        p5 = new fv6("MicMutedStroke", 286, "micmuted", ar6Var2);
        q5 = new fv6("ModeDark", 287, "modedark", ar6Var);
        r5 = new fv6("ModeDarkStroke", 288, "modedark", ar6Var2);
        s5 = new fv6("ModeLight", 289, "modelight", ar6Var);
        t5 = new fv6("ModeLightStroke", 290, "modelight", ar6Var2);
        u5 = new fv6("ModeTheme", 291, "modetheme", ar6Var);
        v5 = new fv6("ModeThemeStroke", 292, "modetheme", ar6Var2);
        w5 = new fv6("MilitaryService", 293, "militaryservice", ar6Var);
        x5 = new fv6("MilitaryServiceStroke", 294, "militaryservice", ar6Var2);
        y5 = new fv6("Minimize", 295, "minimize", ar6Var);
        z5 = new fv6("MinimizeStroke", 296, "minimize", ar6Var2);
        A5 = new fv6("Minus", 297, "minus", ar6Var);
        B5 = new fv6("MinusStroke", 298, "minus", ar6Var2);
        C5 = new fv6("MinusCircle", 299, "minuscircle", ar6Var);
        D5 = new fv6("MinusCircleStroke", 300, "minuscircle", ar6Var2);
        E5 = new fv6("Mobile", 301, "mobile", ar6Var);
        F5 = new fv6("MobileStroke", 302, "mobile", ar6Var2);
        G5 = new fv6("MoneyStack", 303, "moneystack", ar6Var);
        H5 = new fv6("MoneyStackStroke", 304, "moneystack", ar6Var2);
        I5 = new fv6("MoreHorizontal", 305, "morehorizontal", ar6Var);
        J5 = new fv6("MoreHorizontalStroke", 306, "morehorizontal", ar6Var2);
        K5 = new fv6("MoreVertical", 307, "morevertical", ar6Var);
        L5 = new fv6("MoreVerticalStroke", 308, "morevertical", ar6Var2);
        M5 = new fv6("MoveSection", 309, "movesection", ar6Var);
        N5 = new fv6("MoveSectionStroke", 310, "movesection", ar6Var2);
        O5 = new fv6("MoveToFolder", 311, "movetofolder", ar6Var);
        P5 = new fv6("MoveToFolderStroke", 312, "movetofolder", ar6Var2);
        Q5 = new fv6("MyContributions", 313, "mycontributions", ar6Var);
        R5 = new fv6("MyContributionsStroke", 314, "mycontributions", ar6Var2);
        S5 = new fv6("MyPage", 315, "mypage", ar6Var);
        T5 = new fv6("MyPageStroke", 316, "mypage", ar6Var2);
        U5 = new fv6("NativeAndroidArrowBack", 317, "nativeandroidarrowback", ar6Var);
        V5 = new fv6("NativeAndroidArrowBackStroke", 318, "nativeandroidarrowback", ar6Var2);
        W5 = new fv6("NativeAndroidArrowForward", 319, "nativeandroidarrowforward", ar6Var);
        X5 = new fv6("NativeAndroidArrowForwardStroke", 320, "nativeandroidarrowforward", ar6Var2);
        Y5 = new fv6("NativeAndroidMore", 321, "nativeandroidmore", ar6Var);
        Z5 = new fv6("NativeAndroidMoreStroke", 322, "nativeandroidmore", ar6Var2);
        a6 = new fv6("NativeAndroidShare", 323, "nativeandroidshare", ar6Var);
        b6 = new fv6("NativeAndroidShareStroke", 324, "nativeandroidshare", ar6Var2);
        c6 = new fv6("NativeIosChevronBack", 325, "nativeioschevronback", ar6Var);
        d6 = new fv6("NativeIosChevronBackStroke", 326, "nativeioschevronback", ar6Var2);
        e6 = new fv6("NativeIosChevronForward", 327, "nativeioschevronforward", ar6Var);
        f6 = new fv6("NativeIosChevronForwardStroke", 328, "nativeioschevronforward", ar6Var2);
        g6 = new fv6("NativeIosMore", 329, "nativeiosmore", ar6Var);
        h6 = new fv6("NativeIosMoreStroke", 330, "nativeiosmore", ar6Var2);
        i6 = new fv6("NativeIosSafari", 331, "nativeiossafari", ar6Var);
        j6 = new fv6("NativeIosSafariStroke", 332, "nativeiossafari", ar6Var2);
        k6 = new fv6("NativeIosShare", 333, "nativeiosshare", ar6Var);
        l6 = new fv6("NativeIosShareStroke", 334, "nativeiosshare", ar6Var2);
        m6 = new fv6("NativeIosTextFormat", 335, "nativeiostextformat", ar6Var);
        n6 = new fv6("NativeIosTextFormatStroke", 336, "nativeiostextformat", ar6Var2);
        o6 = new fv6("NewWindow", 337, "newwindow", ar6Var);
        p6 = new fv6("NewWindowStroke", 338, "newwindow", ar6Var2);
        q6 = new fv6("Notes", 339, "notes", ar6Var);
        r6 = new fv6("NotesStroke", 340, "notes", ar6Var2);
        s6 = new fv6("Notification", 341, "notification", ar6Var);
        t6 = new fv6("NotificationStroke", 342, "notification", ar6Var2);
        u6 = new fv6("NotificationMuted", 343, "notificationmuted", ar6Var);
        v6 = new fv6("NotificationMutedStroke", 344, "notificationmuted", ar6Var2);
        w6 = new fv6("NumberedList", 345, "numberedlist", ar6Var);
        x6 = new fv6("NumberedListStroke", 346, "numberedlist", ar6Var2);
        y6 = new fv6("Occupation", 347, "occupation", ar6Var);
        z6 = new fv6("OccupationStroke", 348, "occupation", ar6Var2);
        A6 = new fv6("OpenDoor", 349, "opendoor", ar6Var);
        B6 = new fv6("OpenDoorStroke", 350, "opendoor", ar6Var2);
        C6 = new fv6("Patent", 351, "patent", ar6Var);
        D6 = new fv6("PatentStroke", 352, "patent", ar6Var2);
        E6 = new fv6("Pause", 353, "pause", ar6Var);
        F6 = new fv6("PauseStroke", 354, "pause", ar6Var2);
        G6 = new fv6("Pending", 355, "pending", ar6Var);
        H6 = new fv6("PendingStroke", 356, "pending", ar6Var2);
        I6 = new fv6("People", 357, "people", ar6Var);
        J6 = new fv6("PeopleStroke", 358, "people", ar6Var2);
        K6 = new fv6("PersonSearch", 359, "personsearch", ar6Var);
        L6 = new fv6("PersonSearchStroke", 360, "personsearch", ar6Var2);
        M6 = new fv6("Phone", 361, "phone", ar6Var);
        N6 = new fv6("PhoneStroke", 362, "phone", ar6Var2);
        O6 = new fv6("PhoneIn", 363, "phonein", ar6Var);
        P6 = new fv6("PhoneInStroke", 364, "phonein", ar6Var2);
        Q6 = new fv6("PhoneInMiss", 365, "phoneinmiss", ar6Var);
        R6 = new fv6("PhoneInMissStroke", 366, "phoneinmiss", ar6Var2);
        S6 = new fv6("PhoneOut", 367, "phoneout", ar6Var);
        T6 = new fv6("PhoneOutStroke", 368, "phoneout", ar6Var2);
        U6 = new fv6("PhoneOutMiss", 369, "phoneoutmiss", ar6Var);
        V6 = new fv6("PhoneOutMissStroke", 370, "phoneoutmiss", ar6Var2);
        W6 = new fv6("Pin", 371, "pin", ar6Var);
        X6 = new fv6("PinStroke", 372, "pin", ar6Var2);
        Y6 = new fv6("Placeholder", 373, "placeholder", ar6Var);
        Z6 = new fv6("PlaceholderStroke", 374, "placeholder", ar6Var2);
        a7 = new fv6("Plane", 375, "plane", ar6Var);
        b7 = new fv6("PlaneStroke", 376, "plane", ar6Var2);
        c7 = new fv6("Play", 377, "play", ar6Var);
        d7 = new fv6("PlayStroke", 378, "play", ar6Var2);
        e7 = new fv6("Plus", 379, "plus", ar6Var);
        f7 = new fv6("PlusStroke", 380, "plus", ar6Var2);
        g7 = new fv6("PlusCircle", 381, "pluscircle", ar6Var);
        h7 = new fv6("PlusCircleStroke", 382, "pluscircle", ar6Var2);
        i7 = new fv6("PostJob", 383, "postjob", ar6Var);
        j7 = new fv6("PostJobStroke", 384, "postjob", ar6Var2);
        k7 = new fv6("Print", 385, "print", ar6Var);
        l7 = new fv6("PrintStroke", 386, "print", ar6Var2);
        m7 = new fv6("PremiumLogoIcon", 387, "premiumlogoicon", ar6Var);
        n7 = new fv6("PremiumLogoIconStroke", 388, "premiumlogoicon", ar6Var2);
        o7 = new fv6("Profile", 389, "profile", ar6Var);
        p7 = new fv6("ProfileStroke", 390, "profile", ar6Var2);
        q7 = new fv6("ProfileCircle", 391, "profilecircle", ar6Var);
        r7 = new fv6("ProfileCircleStroke", 392, "profilecircle", ar6Var2);
        s7 = new fv6("PromotionalOpportunity", 393, "promotionalopportunity", ar6Var);
        t7 = new fv6("PromotionalOpportunityStroke", 394, "promotionalopportunity", ar6Var2);
        u7 = new fv6("Publication", 395, "publication", ar6Var);
        v7 = new fv6("PublicationStroke", 396, "publication", ar6Var2);
        w7 = new fv6("Question", 397, "question", ar6Var);
        x7 = new fv6("QuestionStroke", 398, "question", ar6Var2);
        y7 = new fv6("QuestionCircle", 399, "questioncircle", ar6Var);
        z7 = new fv6("QuestionCircleStroke", DataOkHttpUploader.HTTP_BAD_REQUEST, "questioncircle", ar6Var2);
        A7 = new fv6("Quotation", DataOkHttpUploader.HTTP_UNAUTHORIZED, "quotation", ar6Var);
        B7 = new fv6("QuotationStroke", 402, "quotation", ar6Var2);
        C7 = new fv6("QuickApply", DataOkHttpUploader.HTTP_FORBIDDEN, "quickapply", ar6Var);
        D7 = new fv6("QuickApplyStroke", 404, "quickapply", ar6Var2);
        E7 = new fv6("QuickInterview", 405, "quickinterview", ar6Var);
        F7 = new fv6("QuickInterviewStroke", 406, "quickinterview", ar6Var2);
        G7 = new fv6("RearrangeItems", 407, "rearrangeitems", ar6Var);
        H7 = new fv6("RearrangeItemsStroke", DataOkHttpUploader.HTTP_CLIENT_TIMEOUT, "rearrangeitems", ar6Var2);
        I7 = new fv6("RecentSearch", 409, "recentsearch", ar6Var);
        J7 = new fv6("RecentSearchStroke", 410, "recentsearch", ar6Var2);
        K7 = new fv6("Record", 411, "record", ar6Var);
        L7 = new fv6("RecordStroke", 412, "record", ar6Var2);
        M7 = new fv6("Refresh", DataOkHttpUploader.HTTP_ENTITY_TOO_LARGE, "refresh", ar6Var);
        N7 = new fv6("RefreshStroke", 414, "refresh", ar6Var2);
        O7 = new fv6("Remote", 415, "remote", ar6Var);
        P7 = new fv6("RemoteStroke", 416, "remote", ar6Var2);
        Q7 = new fv6("RemovePerson", 417, "removeperson", ar6Var);
        R7 = new fv6("RemovePersonStroke", 418, "removeperson", ar6Var2);
        S7 = new fv6("Renew", 419, "renew", ar6Var);
        T7 = new fv6("RenewStroke", 420, "renew", ar6Var2);
        U7 = new fv6("ReplaceFile", 421, "replacefile", ar6Var);
        V7 = new fv6("ReplaceFileStroke", 422, "replacefile", ar6Var2);
        W7 = new fv6("Reply", 423, "reply", ar6Var);
        X7 = new fv6("ReplyStroke", 424, "reply", ar6Var2);
        Y7 = new fv6("ReplyAll", 425, "replyall", ar6Var);
        Z7 = new fv6("ReplyAllStroke", 426, "replyall", ar6Var2);
        a8 = new fv6("Report", 427, "report", ar6Var);
        b8 = new fv6("ReportStroke", 428, "report", ar6Var2);
        c8 = new fv6("Reset", DataOkHttpUploader.HTTP_TOO_MANY_REQUESTS, "reset", ar6Var);
        d8 = new fv6("ResetStroke", 430, "reset", ar6Var2);
        e8 = new fv6("Restore", 431, "restore", ar6Var);
        f8 = new fv6("RestoreStroke", 432, "restore", ar6Var2);
        g8 = new fv6("Responsive", 433, "responsive", ar6Var);
        h8 = new fv6("ResponsiveStroke", 434, "responsive", ar6Var2);
        i8 = new fv6("Resume", 435, "resume", ar6Var);
        j8 = new fv6("ResumeStroke", 436, "resume", ar6Var2);
        k8 = new fv6("Salary", 437, "salary", ar6Var);
        l8 = new fv6("SalaryStroke", 438, "salary", ar6Var2);
        m8 = new fv6("SalaryDollar", 439, "salarydollar", ar6Var);
        n8 = new fv6("SalaryDollarStroke", 440, "salarydollar", ar6Var2);
        o8 = new fv6("SalaryEuro", 441, "salaryeuro", ar6Var);
        p8 = new fv6("SalaryEuroStroke", 442, "salaryeuro", ar6Var2);
        q8 = new fv6("SalaryPound", 443, "salarypound", ar6Var);
        r8 = new fv6("SalaryPoundStroke", 444, "salarypound", ar6Var2);
        s8 = new fv6("SalaryRupee", 445, "salaryrupee", ar6Var);
        t8 = new fv6("SalaryRupeeStroke", 446, "salaryrupee", ar6Var2);
        u8 = new fv6("SalaryYen", 447, "salaryyen", ar6Var);
        v8 = new fv6("SalaryYenStroke", 448, "salaryyen", ar6Var2);
        w8 = new fv6("Save", 449, "save", ar6Var);
        x8 = new fv6("SaveStroke", 450, "save", ar6Var2);
        y8 = new fv6("Seasonal", 451, "seasonal", ar6Var);
        z8 = new fv6("SeasonalStroke", 452, "seasonal", ar6Var2);
        A8 = new fv6("SaveSearch", 453, "savesearch", ar6Var);
        B8 = new fv6("SaveSearchStroke", 454, "savesearch", ar6Var2);
        C8 = new fv6("Search", 455, "search", ar6Var);
        D8 = new fv6("SearchStroke", 456, "search", ar6Var2);
        E8 = new fv6("SearchSaved", 457, "searchsaved", ar6Var);
        F8 = new fv6("SearchSavedStroke", 458, "searchsaved", ar6Var2);
        G8 = new fv6("ScoutLogoIcon", 459, "scoutlogoicon", ar6Var);
        H8 = new fv6("ScoutLogoIconStroke", 460, "scoutlogoicon", ar6Var2);
        I8 = new fv6("Settings", 461, "settings", ar6Var);
        J8 = new fv6("SettingsStroke", 462, "settings", ar6Var2);
        K8 = new fv6("Share", 463, "share", ar6Var);
        L8 = new fv6("ShareStroke", 464, "share", ar6Var2);
        M8 = new fv6("ShareScreen", 465, "sharescreen", ar6Var);
        N8 = new fv6("ShareScreenStroke", 466, "sharescreen", ar6Var2);
        O8 = new fv6("ShareScreenStop", 467, "sharescreenstop", ar6Var);
        P8 = new fv6("ShareScreenStopStroke", 468, "sharescreenstop", ar6Var2);
        Q8 = new fv6("Show", 469, "show", ar6Var);
        R8 = new fv6("ShowStroke", 470, "show", ar6Var2);
        S8 = new fv6("SignOut", 471, "signout", ar6Var);
        T8 = new fv6("SignOutStroke", 472, "signout", ar6Var2);
        U8 = new fv6("Skills", 473, "skills", ar6Var);
        V8 = new fv6("SkillsStroke", 474, "skills", ar6Var2);
        W8 = new fv6("Sms", 475, "sms", ar6Var);
        X8 = new fv6("SmsStroke", 476, "sms", ar6Var2);
        Y8 = new fv6("SortAscending", 477, "sortascending", ar6Var);
        Z8 = new fv6("SortAscendingStroke", 478, "sortascending", ar6Var2);
        a9 = new fv6("SortDescending", 479, "sortdescending", ar6Var);
        b9 = new fv6("SortDescendingStroke", 480, "sortdescending", ar6Var2);
        c9 = new fv6("Spam", 481, "spam", ar6Var);
        d9 = new fv6("SpamStroke", 482, "spam", ar6Var2);
        e9 = new fv6("Speak", 483, "speak", ar6Var);
        f9 = new fv6("SpeakStroke", 484, "speak", ar6Var2);
        g9 = new fv6("Speakers", 485, "speakers", ar6Var);
        h9 = new fv6("SpeakersStroke", 486, "speakers", ar6Var2);
        i9 = new fv6("SpeakersMuted", 487, "speakersmuted", ar6Var);
        j9 = new fv6("SpeakersMutedStroke", 488, "speakersmuted", ar6Var2);
        k9 = new fv6("SpacingComfortable", 489, "spacingcomfortable", ar6Var);
        l9 = new fv6("SpacingComfortableStroke", 490, "spacingcomfortable", ar6Var2);
        m9 = new fv6("SpacingCompact", 491, "spacingcompact", ar6Var);
        n9 = new fv6("SpacingCompactStroke", 492, "spacingcompact", ar6Var2);
        o9 = new fv6("Star", 493, "star", ar6Var);
        p9 = new fv6("StarStroke", 494, "star", ar6Var2);
        q9 = new fv6("Sprout", 495, "sprout", ar6Var);
        r9 = new fv6("SproutStroke", 496, "sprout", ar6Var2);
        s9 = new fv6("StarHalf", 497, "starhalf", ar6Var);
        t9 = new fv6("StarHalfStroke", 498, "starhalf", ar6Var2);
        u9 = new fv6("Stop", 499, "stop", ar6Var);
        v9 = new fv6("StopStroke", 500, "stop", ar6Var2);
        w9 = new fv6("Stopwatch", 501, "stopwatch", ar6Var);
        x9 = new fv6("StopwatchStroke", DataOkHttpUploader.HTTP_BAD_GATEWAY, "stopwatch", ar6Var2);
        y9 = new fv6("Storybook", DataOkHttpUploader.HTTP_UNAVAILABLE, "storybook", ar6Var);
        z9 = new fv6("StorybookStroke", DataOkHttpUploader.HTTP_GATEWAY_TIMEOUT, "storybook", ar6Var2);
        A9 = new fv6("Summary", 505, "summary", ar6Var);
        B9 = new fv6("SummaryStroke", 506, "summary", ar6Var2);
        C9 = new fv6("SuperPopular", DataOkHttpUploader.HTTP_INSUFFICIENT_STORAGE, "superpopular", ar6Var);
        D9 = new fv6("SuperPopularStroke", 508, "superpopular", ar6Var2);
        E9 = new fv6("SwitchLanguageHindi", 509, "switchlanguagehindi", ar6Var);
        F9 = new fv6("SwitchLanguageHindiStroke", 510, "switchlanguagehindi", ar6Var2);
        G9 = new fv6("ThumbsDown", 511, "thumbsdown", ar6Var);
        H9 = new fv6("ThumbsDownStroke", IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING, "thumbsdown", ar6Var2);
        I9 = new fv6("ThumbsUp", 513, "thumbsup", ar6Var);
        J9 = new fv6("ThumbsUpStroke", 514, "thumbsup", ar6Var2);
        K9 = new fv6("Train", 515, "train", ar6Var);
        L9 = new fv6("TrainStroke", 516, "train", ar6Var2);
        M9 = new fv6("TrashCan", 517, "trashcan", ar6Var);
        N9 = new fv6("TrashCanStroke", 518, "trashcan", ar6Var2);
        O9 = new fv6("Truck", 519, "truck", ar6Var);
        P9 = new fv6("TruckStroke", 520, "truck", ar6Var2);
        Q9 = new fv6("Twitter", 521, "twitter", ar6Var);
        R9 = new fv6("TwitterStroke", 522, "twitter", ar6Var2);
        S9 = new fv6("Underline", 523, "underline", ar6Var);
        T9 = new fv6("UnderlineStroke", 524, "underline", ar6Var2);
        U9 = new fv6("Unlock", 525, "unlock", ar6Var);
        V9 = new fv6("UnlockStroke", 526, "unlock", ar6Var2);
        W9 = new fv6("Upload", 527, "upload", ar6Var);
        X9 = new fv6("UploadStroke", 528, "upload", ar6Var2);
        Y9 = new fv6("Upsell", 529, "upsell", ar6Var);
        Z9 = new fv6("UpsellStroke", 530, "upsell", ar6Var2);
        aa = new fv6("UrgentlyHiringIndia", 531, "urgentlyhiringindia", ar6Var);
        ba = new fv6("UrgentlyHiringIndiaStroke", 532, "urgentlyhiringindia", ar6Var2);
        ca = new fv6("Video", 533, MediaStreamTrack.VIDEO_TRACK_KIND, ar6Var);
        da = new fv6("VideoStroke", 534, MediaStreamTrack.VIDEO_TRACK_KIND, ar6Var2);
        ea = new fv6("Waffle", 535, "waffle", ar6Var);
        fa = new fv6("WaffleStroke", 536, "waffle", ar6Var2);
        ga = new fv6("Walking", 537, "walking", ar6Var);
        ha = new fv6("WalkingStroke", 538, "walking", ar6Var2);
        ia = new fv6("Warning", 539, "warning", ar6Var);
        ja = new fv6("WarningStroke", 540, "warning", ar6Var2);
        ka = new fv6("Webpage", 541, "webpage", ar6Var);
        la = new fv6("WebpageStroke", 542, "webpage", ar6Var2);
        ma = new fv6("Webhook", 543, "webhook", ar6Var);
        na = new fv6("WebhookStroke", 544, "webhook", ar6Var2);
        oa = new fv6("WhatsApp", 545, "whatsapp", ar6Var);
        pa = new fv6("WhatsAppStroke", 546, "whatsapp", ar6Var2);
        qa = new fv6("Workflow", 547, "workflow", ar6Var);
        ra = new fv6("WorkflowStroke", 548, "workflow", ar6Var2);
        sa = new fv6("X", 549, "x", ar6Var);
        ta = new fv6("XStroke", 550, "x", ar6Var2);
        ua = new fv6("YouTube", 551, "youtube", ar6Var);
        va = new fv6("YouTubeStroke", 552, "youtube", ar6Var2);
        fv6[] fv6VarArrA = a();
        wa = fv6VarArrA;
        xa = ojh.k(fv6VarArrA);
    }

    public fv6(String str, int i, String str2, ar6 ar6Var) {
        this.rawValue = str2;
        this.variant = ar6Var;
    }

    public static final /* synthetic */ fv6[] a() {
        return new fv6[]{a, b, c, d, e, f, V, W, X, Y, Z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, a3, b3, c3, d3, e3, f3, g3, h3, i3, j3, k3, l3, m3, n3, o3, p3, q3, r3, s3, t3, u3, v3, w3, x3, y3, z3, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3, Y3, Z3, a4, b4, c4, d4, e4, f4, g4, h4, i4, j4, k4, l4, m4, n4, o4, p4, q4, r4, s4, t4, u4, v4, w4, x4, y4, z4, A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, L4, M4, N4, O4, P4, Q4, R4, S4, T4, U4, V4, W4, X4, Y4, Z4, a5, b5, c5, d5, e5, f5, g5, h5, i5, j5, k5, l5, m5, n5, o5, p5, q5, r5, s5, t5, u5, v5, w5, x5, y5, z5, A5, B5, C5, D5, E5, F5, G5, H5, I5, J5, K5, L5, M5, N5, O5, P5, Q5, R5, S5, T5, U5, V5, W5, X5, Y5, Z5, a6, b6, c6, d6, e6, f6, g6, h6, i6, j6, k6, l6, m6, n6, o6, p6, q6, r6, s6, t6, u6, v6, w6, x6, y6, z6, A6, B6, C6, D6, E6, F6, G6, H6, I6, J6, K6, L6, M6, N6, O6, P6, Q6, R6, S6, T6, U6, V6, W6, X6, Y6, Z6, a7, b7, c7, d7, e7, f7, g7, h7, i7, j7, k7, l7, m7, n7, o7, p7, q7, r7, s7, t7, u7, v7, w7, x7, y7, z7, A7, B7, C7, D7, E7, F7, G7, H7, I7, J7, K7, L7, M7, N7, O7, P7, Q7, R7, S7, T7, U7, V7, W7, X7, Y7, Z7, a8, b8, c8, d8, e8, f8, g8, h8, i8, j8, k8, l8, m8, n8, o8, p8, q8, r8, s8, t8, u8, v8, w8, x8, y8, z8, A8, B8, C8, D8, E8, F8, G8, H8, I8, J8, K8, L8, M8, N8, O8, P8, Q8, R8, S8, T8, U8, V8, W8, X8, Y8, Z8, a9, b9, c9, d9, e9, f9, g9, h9, i9, j9, k9, l9, m9, n9, o9, p9, q9, r9, s9, t9, u9, v9, w9, x9, y9, z9, A9, B9, C9, D9, E9, F9, G9, H9, I9, J9, K9, L9, M9, N9, O9, P9, Q9, R9, S9, T9, U9, V9, W9, X9, Y9, Z9, aa, ba, ca, da, ea, fa, ga, ha, ia, ja, ka, la, ma, na, oa, pa, qa, ra, sa, ta, ua, va};
    }

    public static fv6 valueOf(String str) {
        return (fv6) Enum.valueOf(fv6.class, str);
    }

    public static fv6[] values() {
        return (fv6[]) wa.clone();
    }

    public final String c() {
        return this.rawValue;
    }

    public final ar6 e() {
        return this.variant;
    }
}
