package defpackage;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public final class gac {
    public static final int[] a = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, com.indeed.android.jobsearch.R.attr.disableDependentsState, com.indeed.android.jobsearch.R.attr.summaryOff, com.indeed.android.jobsearch.R.attr.summaryOn};
    public static final int[] b = {R.attr.dialogTitle, R.attr.dialogMessage, R.attr.dialogIcon, R.attr.positiveButtonText, R.attr.negativeButtonText, R.attr.dialogLayout, com.indeed.android.jobsearch.R.attr.dialogIcon, com.indeed.android.jobsearch.R.attr.dialogLayout, com.indeed.android.jobsearch.R.attr.dialogMessage, com.indeed.android.jobsearch.R.attr.dialogTitle, com.indeed.android.jobsearch.R.attr.negativeButtonText, com.indeed.android.jobsearch.R.attr.positiveButtonText};
    public static final int[] c = {com.indeed.android.jobsearch.R.attr.useSimpleSummaryProvider};
    public static final int[] d = {R.attr.entries, R.attr.entryValues, com.indeed.android.jobsearch.R.attr.entries, com.indeed.android.jobsearch.R.attr.entryValues, com.indeed.android.jobsearch.R.attr.useSimpleSummaryProvider};
    public static final int[] e = {R.attr.entries, R.attr.entryValues, com.indeed.android.jobsearch.R.attr.entries, com.indeed.android.jobsearch.R.attr.entryValues};
    public static final int[] f = {R.attr.icon, R.attr.persistent, R.attr.enabled, R.attr.layout, R.attr.title, R.attr.selectable, R.attr.key, R.attr.summary, R.attr.order, R.attr.widgetLayout, R.attr.dependency, R.attr.defaultValue, R.attr.shouldDisableView, R.attr.fragment, R.attr.singleLineTitle, R.attr.iconSpaceReserved, com.indeed.android.jobsearch.R.attr.allowDividerAbove, com.indeed.android.jobsearch.R.attr.allowDividerBelow, com.indeed.android.jobsearch.R.attr.defaultValue, com.indeed.android.jobsearch.R.attr.dependency, com.indeed.android.jobsearch.R.attr.enableCopying, com.indeed.android.jobsearch.R.attr.enabled, com.indeed.android.jobsearch.R.attr.fragment, com.indeed.android.jobsearch.R.attr.icon, com.indeed.android.jobsearch.R.attr.iconSpaceReserved, com.indeed.android.jobsearch.R.attr.isPreferenceVisible, com.indeed.android.jobsearch.R.attr.key, com.indeed.android.jobsearch.R.attr.layout, com.indeed.android.jobsearch.R.attr.order, com.indeed.android.jobsearch.R.attr.persistent, com.indeed.android.jobsearch.R.attr.selectable, com.indeed.android.jobsearch.R.attr.shouldDisableView, com.indeed.android.jobsearch.R.attr.singleLineTitle, com.indeed.android.jobsearch.R.attr.summary, com.indeed.android.jobsearch.R.attr.title, com.indeed.android.jobsearch.R.attr.widgetLayout};
    public static final int[] g = {R.attr.orderingFromXml, com.indeed.android.jobsearch.R.attr.initialExpandedChildrenCount, com.indeed.android.jobsearch.R.attr.orderingFromXml};
    public static final int[] h = {R.attr.maxWidth, R.attr.maxHeight, com.indeed.android.jobsearch.R.attr.maxHeight, com.indeed.android.jobsearch.R.attr.maxWidth};
    public static final int[] i = {R.attr.layout, R.attr.max, com.indeed.android.jobsearch.R.attr.adjustable, com.indeed.android.jobsearch.R.attr.min, com.indeed.android.jobsearch.R.attr.seekBarIncrement, com.indeed.android.jobsearch.R.attr.showSeekBarValue, com.indeed.android.jobsearch.R.attr.updatesContinuously};
    public static final int[] j = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, com.indeed.android.jobsearch.R.attr.disableDependentsState, com.indeed.android.jobsearch.R.attr.summaryOff, com.indeed.android.jobsearch.R.attr.summaryOn, com.indeed.android.jobsearch.R.attr.switchTextOff, com.indeed.android.jobsearch.R.attr.switchTextOn};
    public static final int[] k = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, com.indeed.android.jobsearch.R.attr.disableDependentsState, com.indeed.android.jobsearch.R.attr.summaryOff, com.indeed.android.jobsearch.R.attr.summaryOn, com.indeed.android.jobsearch.R.attr.switchTextOff, com.indeed.android.jobsearch.R.attr.switchTextOn};
}
