package defpackage;

import defpackage.ao2;
import defpackage.c5d;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/* JADX INFO: loaded from: classes2.dex */
public final class og7 {
    public static final og7 z = new og7(ao2.a.a);
    public final ao2 a;
    public final boolean b;
    public final boolean c;
    public final boolean d;
    public final boolean e;
    public final boolean f;
    public final boolean g;
    public final boolean h;
    public final ArrayList i;
    public final String j;
    public final String k;
    public final String l;
    public final ArrayList m;
    public final HashSet n;
    public final ArrayList o;
    public final c5d.b p;
    public final boolean q;
    public final boolean r;
    public final int s;
    public final boolean t;
    public final boolean u;
    public final boolean v;
    public final Map<String, Set<String>> w;
    public final Map<String, Set<String>> x;
    public final boolean y;

    public og7(ao2 ao2Var) {
        this.a = ao2Var;
        ao2Var.c("integrations.enabled", true);
        this.b = true;
        ao2Var.c("trace.enabled", true);
        this.c = true;
        ao2Var.c("trace.otel.enabled", false);
        this.d = false;
        ao2Var.c("trace.128.bit.traceid.logging.enabled", false);
        this.e = false;
        ao2Var.c("profiling.enabled", false);
        this.f = false;
        ao2Var.c("instrumentation.telemetry.enabled", true);
        this.g = true;
        ao2Var.c("trace.executors.all", false);
        this.h = false;
        ao2Var.g("trace.executors");
        List list = Collections.EMPTY_LIST;
        this.i = new ArrayList(list);
        ao2Var.g("trace.thread-pool-executors.exclude");
        new HashSet(list);
        ao2Var.j("trace.jdbc.prepared.statement.class.name", "");
        this.j = "";
        ao2Var.j("trace.jdbc.connection.class.name", "");
        this.k = "";
        ao2Var.j("trace.http.url.connection.class.name", "");
        this.l = "";
        ao2Var.c("profiling.directallocation.enabled", false);
        ao2Var.g("trace.classes.exclude");
        this.m = new ArrayList(list);
        ao2Var.j("trace.classes.exclude.file", null);
        ao2Var.g("trace.classloaders.exclude");
        this.n = new HashSet(list);
        ao2Var.g("trace.codesources.exclude");
        this.o = new ArrayList(list);
        ao2Var.j("resolver.cache.config", null);
        wn2 wn2Var = wn2.b;
        c5d.b bVar = c5d.a;
        wn2Var.a("resolver.cache.config", 4, String.valueOf(bVar));
        this.p = bVar;
        ao2Var.j("resolver.cache.dir", null);
        ao2Var.c("resolver.names.are.unique", false);
        this.q = false;
        ao2Var.c("resolver.use.loadclass", true);
        this.r = true;
        ao2Var.b(null, "resolver.use.url.caches");
        ao2Var.e(300, "resolver.reset.interval");
        this.s = 300;
        ao2Var.c("trace.runtime.context.field.injection", true);
        this.t = true;
        ao2Var.c("trace.serialversionuid.field.injection", true);
        this.u = true;
        BitSet bitSet = zn2.a;
        ao2Var.j("trace.annotations", null);
        ao2Var.c("trace.annotation.async", false);
        this.v = false;
        ao2Var.j("trace.methods", null);
        this.w = Collections.EMPTY_MAP;
        ao2Var.j("measure.methods", "");
        this.x = nn2.x("");
        ao2Var.c("trace.internal.exit.on.failure", false);
        this.y = false;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("InstrumenterConfig{integrationsEnabled=");
        sb.append(this.b);
        sb.append(", traceEnabled=");
        sb.append(this.c);
        sb.append(", traceOtelEnabled=");
        sb.append(this.d);
        sb.append(", logs128bTraceIdEnabled=");
        sb.append(this.e);
        sb.append(", profilingEnabled=");
        sb.append(this.f);
        sb.append(", telemetryEnabled=");
        sb.append(this.g);
        sb.append(", traceExecutorsAll=");
        sb.append(this.h);
        sb.append(", traceExecutors=");
        sb.append(this.i);
        sb.append(", jdbcPreparedStatementClassName='");
        sb.append(this.j);
        sb.append("', jdbcConnectionClassName='");
        sb.append(this.k);
        sb.append("', httpURLConnectionClassName='");
        sb.append(this.l);
        sb.append("', excludedClasses=");
        sb.append(this.m);
        sb.append(", excludedClassesFile=null, excludedClassLoaders=");
        sb.append(this.n);
        sb.append(", excludedCodeSources=");
        sb.append(this.o);
        sb.append(", resolverCacheConfig=");
        sb.append(this.p);
        sb.append(", resolverCacheDir=null, resolverNamesAreUnique=");
        sb.append(this.q);
        sb.append(", resolverUseLoadClass=");
        sb.append(this.r);
        sb.append(", resolverUseUrlCaches=null, resolverResetInterval=");
        sb.append(this.s);
        sb.append(", runtimeContextFieldInjection=");
        sb.append(this.t);
        sb.append(", serialVersionUIDFieldInjection=");
        sb.append(this.u);
        sb.append(", traceAnnotations='null', traceAnnotationAsync=");
        sb.append(this.v);
        sb.append(", traceMethods='");
        sb.append(this.w);
        sb.append("', measureMethods= '");
        sb.append(this.x);
        sb.append("', internalExitOnFailure=");
        return m6.i(sb, this.y, '}');
    }
}
