package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class qa2 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public fq1 K;
    public fq1 L;
    public fq1 M;
    public ux1 N;
    public ux1 O;
    public snf P;
    public snf Q;
    public k32 R;
    public nq6 S;
    public nq6 T;
    public xhc U;
    public zdf V;
    public zdf W;
    public final long a;
    public final long b;
    public final long c;
    public final long d;
    public final long e;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public qa2(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        h5.j(this.a, "onPrimary=", sb);
        h5.j(this.b, "primaryContainer=", sb);
        h5.j(this.c, "onPrimaryContainer=", sb);
        h5.j(this.d, "inversePrimary=", sb);
        h5.j(this.e, "secondary=", sb);
        h5.j(this.f, "onSecondary=", sb);
        h5.j(this.g, "secondaryContainer=", sb);
        h5.j(this.h, "onSecondaryContainer=", sb);
        h5.j(this.i, "tertiary=", sb);
        h5.j(this.j, "onTertiary=", sb);
        h5.j(this.k, "tertiaryContainer=", sb);
        h5.j(this.l, "onTertiaryContainer=", sb);
        h5.j(this.m, "background=", sb);
        h5.j(this.n, "onBackground=", sb);
        h5.j(this.o, "surface=", sb);
        h5.j(this.p, "onSurface=", sb);
        h5.j(this.q, "surfaceVariant=", sb);
        h5.j(this.r, "onSurfaceVariant=", sb);
        h5.j(this.s, "surfaceTint=", sb);
        h5.j(this.t, "inverseSurface=", sb);
        h5.j(this.u, "inverseOnSurface=", sb);
        h5.j(this.v, "error=", sb);
        h5.j(this.w, "onError=", sb);
        h5.j(this.x, "errorContainer=", sb);
        h5.j(this.y, "onErrorContainer=", sb);
        h5.j(this.z, "outline=", sb);
        h5.j(this.A, "outlineVariant=", sb);
        h5.j(this.B, "scrim=", sb);
        h5.j(this.C, "surfaceBright=", sb);
        h5.j(this.D, "surfaceDim=", sb);
        h5.j(this.E, "surfaceContainer=", sb);
        h5.j(this.F, "surfaceContainerHigh=", sb);
        h5.j(this.G, "surfaceContainerHighest=", sb);
        h5.j(this.H, "surfaceContainerLow=", sb);
        h5.j(this.I, "surfaceContainerLowest=", sb);
        sb.append((Object) da2.i(this.J));
        sb.append(')');
        return sb.toString();
    }
}
