package defpackage;

import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/* JADX INFO: loaded from: classes3.dex */
public final class svb {
    public final go4 A;
    public final String B;
    public final List<lu0> C;
    public final boolean D;
    public final mu0 E;
    public final String F;
    public final List<hz1> G;
    public final boolean H;
    public final hz1 I;
    public final hz1 J;
    public final String K;
    public final List<av8> L;
    public final k38 M;
    public final List<wj8> N;
    public final String O;
    public final wj8 P;
    public final List<zie> Q;
    public final List<zie> R;
    public final x73 S;
    public final String T;
    public final zie U;
    public final boolean V;
    public final String W;
    public final boolean X;
    public final String Y;
    public final boolean Z;
    public final String a;
    public final ux8 a0;
    public final String b;
    public final Map<String, ux8> b0;
    public final boolean c;
    public final Set<String> c0;
    public final String d;
    public final j2h e;
    public final j2h f;
    public final List<j2h> g;
    public final Map<String, String> h;
    public final boolean i;
    public final String j;
    public final List<it9> k;
    public final mt9 l;
    public final String m;
    public final List<p6c> n;
    public final boolean o;
    public final r6c p;
    public final String q;
    public final List<n5b> r;
    public final boolean s;
    public final q5b t;
    public final String u;
    public final List<m61> v;
    public final m61 w;
    public final String x;
    public final jo4 y;
    public final Map<String, jo4> z;

    public svb(String str, String str2, boolean z, String str3, j2h j2hVar, j2h j2hVar2, List<j2h> list, Map<String, String> map, boolean z2, String str4, List<it9> list2, mt9 mt9Var, String str5, List<p6c> list3, boolean z3, r6c r6cVar, String str6, List<n5b> list4, boolean z4, q5b q5bVar, String str7, List<m61> list5, m61 m61Var, String str8, jo4 jo4Var, Map<String, jo4> map2, go4 go4Var, String str9, List<lu0> list6, boolean z5, mu0 mu0Var, String str10, List<hz1> list7, boolean z6, hz1 hz1Var, hz1 hz1Var2, String str11, List<av8> list8, k38 k38Var, List<wj8> list9, String str12, wj8 wj8Var, List<zie> list10, List<zie> list11, x73 x73Var, String str13, zie zieVar, boolean z7, String str14, boolean z8, String str15, boolean z9, ux8 ux8Var, Map<String, ux8> map3, Set<String> set) {
        this.a = str;
        this.b = str2;
        this.c = z;
        this.d = str3;
        this.e = j2hVar;
        this.f = j2hVar2;
        this.g = list;
        this.h = map;
        this.i = z2;
        this.j = str4;
        this.k = list2;
        this.l = mt9Var;
        this.m = str5;
        this.n = list3;
        this.o = z3;
        this.p = r6cVar;
        this.q = str6;
        this.r = list4;
        this.s = z4;
        this.t = q5bVar;
        this.u = str7;
        this.v = list5;
        this.w = m61Var;
        this.x = str8;
        this.y = jo4Var;
        this.z = map2;
        this.A = go4Var;
        this.B = str9;
        this.C = list6;
        this.D = z5;
        this.E = mu0Var;
        this.F = str10;
        this.G = list7;
        this.H = z6;
        this.I = hz1Var;
        this.J = hz1Var2;
        this.K = str11;
        this.L = list8;
        this.M = k38Var;
        this.N = list9;
        this.O = str12;
        this.P = wj8Var;
        this.Q = list10;
        this.R = list11;
        this.S = x73Var;
        this.T = str13;
        this.U = zieVar;
        this.V = z7;
        this.W = str14;
        this.X = z8;
        this.Y = str15;
        this.Z = z9;
        this.a0 = ux8Var;
        this.b0 = map3;
        this.c0 = set;
    }

    public static svb a(svb svbVar, String str, String str2, boolean z, String str3, j2h j2hVar, j2h j2hVar2, List list, Map map, boolean z2, String str4, ArrayList arrayList, mt9 mt9Var, String str5, ArrayList arrayList2, boolean z3, r6c r6cVar, String str6, ArrayList arrayList3, boolean z4, q5b q5bVar, String str7, ArrayList arrayList4, m61 m61Var, String str8, jo4 jo4Var, Map map2, go4 go4Var, String str9, ArrayList arrayList5, boolean z5, mu0 mu0Var, String str10, ArrayList arrayList6, boolean z6, hz1 hz1Var, hz1 hz1Var2, String str11, ArrayList arrayList7, k38 k38Var, ArrayList arrayList8, String str12, wj8 wj8Var, ArrayList arrayList9, List list2, x73 x73Var, String str13, zie zieVar, boolean z7, String str14, boolean z8, String str15, boolean z9, ux8 ux8Var, Map map3, LinkedHashSet linkedHashSet, int i, int i2) {
        String str16 = (i & 1) != 0 ? svbVar.a : str;
        String str17 = (i & 2) != 0 ? svbVar.b : str2;
        boolean z10 = (i & 4) != 0 ? svbVar.c : z;
        String str18 = (i & 8) != 0 ? svbVar.d : str3;
        j2h j2hVar3 = (i & 16) != 0 ? svbVar.e : j2hVar;
        j2h j2hVar4 = (i & 32) != 0 ? svbVar.f : j2hVar2;
        List list3 = (i & 64) != 0 ? svbVar.g : list;
        Map map4 = (i & IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT) != 0 ? svbVar.h : map;
        boolean z11 = (i & IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER) != 0 ? svbVar.i : z2;
        String str19 = (i & IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING) != 0 ? svbVar.j : str4;
        List<it9> list4 = (i & IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET) != 0 ? svbVar.k : arrayList;
        mt9 mt9Var2 = (i & 2048) != 0 ? svbVar.l : mt9Var;
        String str20 = (i & 4096) != 0 ? svbVar.m : str5;
        String str21 = str16;
        List<p6c> list5 = (i & 8192) != 0 ? svbVar.n : arrayList2;
        boolean z12 = (i & 16384) != 0 ? svbVar.o : z3;
        r6c r6cVar2 = (i & 32768) != 0 ? svbVar.p : r6cVar;
        String str22 = (i & 65536) != 0 ? svbVar.q : str6;
        List<n5b> list6 = (i & 131072) != 0 ? svbVar.r : arrayList3;
        boolean z13 = (i & 262144) != 0 ? svbVar.s : z4;
        q5b q5bVar2 = (i & 524288) != 0 ? svbVar.t : q5bVar;
        String str23 = (i & 1048576) != 0 ? svbVar.u : str7;
        List<m61> list7 = (i & 2097152) != 0 ? svbVar.v : arrayList4;
        m61 m61Var2 = (i & 4194304) != 0 ? svbVar.w : m61Var;
        String str24 = (i & 8388608) != 0 ? svbVar.x : str8;
        jo4 jo4Var2 = (i & 16777216) != 0 ? svbVar.y : jo4Var;
        Map map5 = (i & 33554432) != 0 ? svbVar.z : map2;
        go4 go4Var2 = (i & 67108864) != 0 ? svbVar.A : go4Var;
        String str25 = (i & 134217728) != 0 ? svbVar.B : str9;
        List<lu0> list8 = (i & 268435456) != 0 ? svbVar.C : arrayList5;
        boolean z14 = (i & 536870912) != 0 ? svbVar.D : z5;
        mu0 mu0Var2 = (i & 1073741824) != 0 ? svbVar.E : mu0Var;
        String str26 = (i & Integer.MIN_VALUE) != 0 ? svbVar.F : str10;
        List<hz1> list9 = (i2 & 1) != 0 ? svbVar.G : arrayList6;
        boolean z15 = (i2 & 2) != 0 ? svbVar.H : z6;
        hz1 hz1Var3 = (i2 & 4) != 0 ? svbVar.I : hz1Var;
        hz1 hz1Var4 = (i2 & 8) != 0 ? svbVar.J : hz1Var2;
        String str27 = (i2 & 16) != 0 ? svbVar.K : str11;
        List<av8> list10 = (i2 & 32) != 0 ? svbVar.L : arrayList7;
        k38 k38Var2 = (i2 & 64) != 0 ? svbVar.M : k38Var;
        List<wj8> list11 = (i2 & IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT) != 0 ? svbVar.N : arrayList8;
        String str28 = (i2 & IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER) != 0 ? svbVar.O : str12;
        wj8 wj8Var2 = (i2 & IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING) != 0 ? svbVar.P : wj8Var;
        List<zie> list12 = (i2 & IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET) != 0 ? svbVar.Q : arrayList9;
        List list13 = (i2 & 2048) != 0 ? svbVar.R : list2;
        x73 x73Var2 = (i2 & 4096) != 0 ? svbVar.S : x73Var;
        String str29 = (i2 & 8192) != 0 ? svbVar.T : str13;
        zie zieVar2 = (i2 & 16384) != 0 ? svbVar.U : zieVar;
        boolean z16 = (i2 & 32768) != 0 ? svbVar.V : z7;
        String str30 = (i2 & 65536) != 0 ? svbVar.W : str14;
        boolean z17 = (i2 & 131072) != 0 ? svbVar.X : z8;
        String str31 = (i2 & 262144) != 0 ? svbVar.Y : str15;
        boolean z18 = (i2 & 524288) != 0 ? svbVar.Z : z9;
        ux8 ux8Var2 = (i2 & 1048576) != 0 ? svbVar.a0 : ux8Var;
        Map map6 = (i2 & 2097152) != 0 ? svbVar.b0 : map3;
        Set<String> set = (i2 & 4194304) != 0 ? svbVar.c0 : linkedHashSet;
        svbVar.getClass();
        str18.getClass();
        list3.getClass();
        map4.getClass();
        str19.getClass();
        list4.getClass();
        str20.getClass();
        list5.getClass();
        str22.getClass();
        list6.getClass();
        str23.getClass();
        list7.getClass();
        str24.getClass();
        map5.getClass();
        str25.getClass();
        list8.getClass();
        str26.getClass();
        list9.getClass();
        str27.getClass();
        list10.getClass();
        list11.getClass();
        list12.getClass();
        list13.getClass();
        ux8Var2.getClass();
        map6.getClass();
        set.getClass();
        return new svb(str21, str17, z10, str18, j2hVar3, j2hVar4, list3, map4, z11, str19, list4, mt9Var2, str20, list5, z12, r6cVar2, str22, list6, z13, q5bVar2, str23, list7, m61Var2, str24, jo4Var2, map5, go4Var2, str25, list8, z14, mu0Var2, str26, list9, z15, hz1Var3, hz1Var4, str27, list10, k38Var2, list11, str28, wj8Var2, list12, list13, x73Var2, str29, zieVar2, z16, str30, z17, str31, z18, ux8Var2, map6, set);
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof svb)) {
            return false;
        }
        svb svbVar = (svb) obj;
        return wl7.b(this.a, svbVar.a) && wl7.b(this.b, svbVar.b) && this.c == svbVar.c && wl7.b(this.d, svbVar.d) && wl7.b(this.e, svbVar.e) && wl7.b(this.f, svbVar.f) && wl7.b(this.g, svbVar.g) && wl7.b(this.h, svbVar.h) && this.i == svbVar.i && wl7.b(this.j, svbVar.j) && wl7.b(this.k, svbVar.k) && wl7.b(this.l, svbVar.l) && wl7.b(this.m, svbVar.m) && wl7.b(this.n, svbVar.n) && this.o == svbVar.o && wl7.b(this.p, svbVar.p) && wl7.b(this.q, svbVar.q) && wl7.b(this.r, svbVar.r) && this.s == svbVar.s && wl7.b(this.t, svbVar.t) && wl7.b(this.u, svbVar.u) && wl7.b(this.v, svbVar.v) && wl7.b(this.w, svbVar.w) && wl7.b(this.x, svbVar.x) && wl7.b(this.y, svbVar.y) && wl7.b(this.z, svbVar.z) && wl7.b(this.A, svbVar.A) && wl7.b(this.B, svbVar.B) && wl7.b(this.C, svbVar.C) && this.D == svbVar.D && wl7.b(this.E, svbVar.E) && wl7.b(this.F, svbVar.F) && wl7.b(this.G, svbVar.G) && this.H == svbVar.H && wl7.b(this.I, svbVar.I) && wl7.b(this.J, svbVar.J) && wl7.b(this.K, svbVar.K) && wl7.b(this.L, svbVar.L) && this.M == svbVar.M && wl7.b(this.N, svbVar.N) && wl7.b(this.O, svbVar.O) && wl7.b(this.P, svbVar.P) && wl7.b(this.Q, svbVar.Q) && wl7.b(this.R, svbVar.R) && wl7.b(this.S, svbVar.S) && wl7.b(this.T, svbVar.T) && wl7.b(this.U, svbVar.U) && this.V == svbVar.V && wl7.b(this.W, svbVar.W) && this.X == svbVar.X && wl7.b(this.Y, svbVar.Y) && this.Z == svbVar.Z && wl7.b(this.a0, svbVar.a0) && wl7.b(this.b0, svbVar.b0) && wl7.b(this.c0, svbVar.c0);
    }

    public final int hashCode() {
        String str = this.a;
        int iHashCode = (str == null ? 0 : str.hashCode()) * 31;
        String str2 = this.b;
        int iD = akb.d(ia.f((iHashCode + (str2 == null ? 0 : str2.hashCode())) * 31, 31, this.c), 31, this.d);
        j2h j2hVar = this.e;
        int iHashCode2 = (iD + (j2hVar == null ? 0 : j2hVar.hashCode())) * 31;
        j2h j2hVar2 = this.f;
        int iG = ia.g(this.k, akb.d(ia.f(k20.b(this.h, ia.g(this.g, (iHashCode2 + (j2hVar2 == null ? 0 : j2hVar2.hashCode())) * 31, 31), 31), 31, this.i), 31, this.j), 31);
        mt9 mt9Var = this.l;
        int iF = ia.f(ia.g(this.n, akb.d((iG + (mt9Var == null ? 0 : mt9Var.hashCode())) * 31, 31, this.m), 31), 31, this.o);
        r6c r6cVar = this.p;
        int iF2 = ia.f(ia.g(this.r, akb.d((iF + (r6cVar == null ? 0 : r6cVar.hashCode())) * 31, 31, this.q), 31), 31, this.s);
        q5b q5bVar = this.t;
        int iG2 = ia.g(this.v, akb.d((iF2 + (q5bVar == null ? 0 : q5bVar.hashCode())) * 31, 31, this.u), 31);
        m61 m61Var = this.w;
        int iD2 = akb.d((iG2 + (m61Var == null ? 0 : m61Var.hashCode())) * 31, 31, this.x);
        jo4 jo4Var = this.y;
        int iB = k20.b(this.z, (iD2 + (jo4Var == null ? 0 : jo4Var.hashCode())) * 31, 31);
        go4 go4Var = this.A;
        int iF3 = ia.f(ia.g(this.C, akb.d((iB + (go4Var == null ? 0 : go4Var.hashCode())) * 31, 31, this.B), 31), 31, this.D);
        mu0 mu0Var = this.E;
        int iF4 = ia.f(ia.g(this.G, akb.d((iF3 + (mu0Var == null ? 0 : mu0Var.hashCode())) * 31, 31, this.F), 31), 31, this.H);
        hz1 hz1Var = this.I;
        int iHashCode3 = (iF4 + (hz1Var == null ? 0 : hz1Var.hashCode())) * 31;
        hz1 hz1Var2 = this.J;
        int iG3 = ia.g(this.L, akb.d((iHashCode3 + (hz1Var2 == null ? 0 : hz1Var2.hashCode())) * 31, 31, this.K), 31);
        k38 k38Var = this.M;
        int iG4 = ia.g(this.N, (iG3 + (k38Var == null ? 0 : k38Var.hashCode())) * 31, 31);
        String str3 = this.O;
        int iHashCode4 = (iG4 + (str3 == null ? 0 : str3.hashCode())) * 31;
        wj8 wj8Var = this.P;
        int iG5 = ia.g(this.R, ia.g(this.Q, (iHashCode4 + (wj8Var == null ? 0 : wj8Var.hashCode())) * 31, 31), 31);
        x73 x73Var = this.S;
        int iHashCode5 = (iG5 + (x73Var == null ? 0 : x73Var.hashCode())) * 31;
        String str4 = this.T;
        int iHashCode6 = (iHashCode5 + (str4 == null ? 0 : str4.hashCode())) * 31;
        zie zieVar = this.U;
        int iF5 = ia.f((iHashCode6 + (zieVar == null ? 0 : zieVar.hashCode())) * 31, 31, this.V);
        String str5 = this.W;
        int iF6 = ia.f((iF5 + (str5 == null ? 0 : str5.hashCode())) * 31, 31, this.X);
        String str6 = this.Y;
        return this.c0.hashCode() + k20.b(this.b0, (this.a0.hashCode() + ia.f((iF6 + (str6 != null ? str6.hashCode() : 0)) * 31, 31, this.Z)) * 31, 31);
    }

    public final String toString() {
        StringBuilder sbF = u40.f("ProfileSectionsState(indeedResumeId=", this.a, ", summary=", this.b, ", summaryIsBuildSuggestion=");
        k6.k(", idOfWorkExperienceToEdit=", this.d, ", profileWorkExperienceToEdit=", sbF, this.c);
        sbF.append(this.e);
        sbF.append(", buildSuggestionWorkExperienceToEdit=");
        sbF.append(this.f);
        sbF.append(", workExperiences=");
        sbF.append(this.g);
        sbF.append(", workExperienceLogoUrls=");
        sbF.append(this.h);
        sbF.append(", workExperienceIsBuildSuggestion=");
        k6.k(", idOfMilitaryServiceToEdit=", this.j, ", militaryServices=", sbF, this.i);
        sbF.append(this.k);
        sbF.append(", suggestedMilitaryServiceItem=");
        sbF.append(this.l);
        sbF.append(", idOfPublicationToEdit=");
        sbF.append(this.m);
        sbF.append(", publications=");
        sbF.append(this.n);
        sbF.append(", publicationIsBuildSuggestion=");
        sbF.append(this.o);
        sbF.append(", profilePublicationToEdit=");
        sbF.append(this.p);
        sbF.append(", idOfPatentToEdit=");
        sbF.append(this.q);
        sbF.append(", patents=");
        sbF.append(this.r);
        sbF.append(", patentIsBuildSuggestion=");
        sbF.append(this.s);
        sbF.append(", profilePatentToEdit=");
        sbF.append(this.t);
        sbF.append(", idOfAwardToEdit=");
        sbF.append(this.u);
        sbF.append(", awards=");
        sbF.append(this.v);
        sbF.append(", suggestedAwardItem=");
        sbF.append(this.w);
        sbF.append(", idOfEducationToEdit=");
        sbF.append(this.x);
        sbF.append(", buildSuggestionEducationToEdit=");
        sbF.append(this.y);
        sbF.append(", educations=");
        sbF.append(this.z);
        sbF.append(", suggestedEducationItem=");
        sbF.append(this.A);
        sbF.append(", idOfGroupToEdit=");
        sbF.append(this.B);
        sbF.append(", groups=");
        sbF.append(this.C);
        sbF.append(", groupIsBuildSuggestion=");
        sbF.append(this.D);
        sbF.append(", profileGroupToEdit=");
        sbF.append(this.E);
        sbF.append(", idOfCertificationToEdit=");
        sbF.append(this.F);
        sbF.append(", certifications=");
        sbF.append(this.G);
        sbF.append(", certificationIsBuildSuggestion=");
        sbF.append(this.H);
        sbF.append(", profileCertificationToEdit=");
        sbF.append(this.I);
        sbF.append(", buildSuggestionCertificationToEdit=");
        sbF.append(this.J);
        sbF.append(", idOfLicenseToEdit=");
        sbF.append(this.K);
        sbF.append(", licenses=");
        sbF.append(this.L);
        sbF.append(", specialLicenseFromLastExperience=");
        sbF.append(this.M);
        sbF.append(", languageSkills=");
        sbF.append(this.N);
        sbF.append(", lastSelectedLanguage=");
        sbF.append(this.O);
        sbF.append(", languageItemToEdit=");
        sbF.append(this.P);
        sbF.append(", skills=");
        l6.q(sbF, this.Q, ", skillsForBuildSuggestion=", this.R, ", skillCrowTaxoSkillModeToEdit=");
        sbF.append(this.S);
        sbF.append(", skillIdToEdit=");
        sbF.append(this.T);
        sbF.append(", skillItemToEdit=");
        sbF.append(this.U);
        sbF.append(", isSkillSetEdit=");
        sbF.append(this.V);
        sbF.append(", skillSetIdToEdit=");
        akb.q(this.W, ", showSuggestedSkillsAlert=", ", additionalInfo=", sbF, this.X);
        akb.q(this.Y, ", additionalInfoIsBuildSuggestion=", ", inputLinkValue=", sbF, this.Z);
        sbF.append(this.a0);
        sbF.append(", links=");
        sbF.append(this.b0);
        sbF.append(", dismissedMissingDetailsAlertIds=");
        sbF.append(this.c0);
        sbF.append(")");
        return sbF.toString();
    }

    public svb() {
        this(0);
    }

    public /* synthetic */ svb(int i) {
        ux8 ux8Var = new ux8("", "");
        is4 is4Var = is4.a;
        zr4 zr4Var = zr4.a;
        bs4 bs4Var = bs4.a;
        this(null, null, false, "", null, null, zr4Var, bs4Var, false, "", zr4Var, null, "", zr4Var, false, null, "", zr4Var, false, null, "", zr4Var, null, "", null, bs4Var, null, "", zr4Var, false, null, "", zr4Var, false, null, null, "", zr4Var, null, zr4Var, null, null, zr4Var, zr4Var, null, null, null, false, null, false, null, false, ux8Var, bs4Var, is4Var);
    }
}
