package defpackage;

/* JADX INFO: loaded from: classes3.dex */
public interface u5h {
    public static final u A;
    public static final u B;
    public static final u C;
    public static final u D;
    public static final u E;
    public static final u F;
    public static final u G;
    public static final u H;
    public static final u I;
    public static final u J;
    public static final u K;
    public static final u L;
    public static final u M;
    public static final u N;
    public static final u O;
    public static final u P;
    public static final u Q;
    public static final u R;
    public static final u r;
    public static final u s;
    public static final u t;
    public static final u u;
    public static final u v;
    public static final u w;
    public static final u x;
    public static final u y;
    public static final u z;

    static {
        u uVar = new u("1.2.840.10045");
        u uVar2 = new u(uVar, "1");
        r = new u(uVar2, "1");
        u uVar3 = new u(uVar2, "2");
        s = uVar3;
        new u(uVar3, "3.1");
        t = new u(uVar3, "3.2");
        u = new u(uVar3, "3.3");
        u uVar4 = new u(uVar, "4");
        new u(uVar4, "1");
        new u(new u(uVar, "2"), "1");
        u uVar5 = new u(uVar4, "3");
        new u(uVar5, "1");
        new u(uVar5, "2");
        new u(uVar5, "3");
        new u(uVar5, "4");
        u uVar6 = new u(uVar, "3");
        u uVar7 = new u(uVar6, "0");
        v = new u(uVar7, "1");
        w = new u(uVar7, "2");
        x = new u(uVar7, "3");
        y = new u(uVar7, "4");
        z = new u(uVar7, "5");
        A = new u(uVar7, "6");
        B = new u(uVar7, "7");
        new u(uVar7, "8");
        new u(uVar7, "9");
        C = new u(uVar7, "10");
        D = new u(uVar7, "11");
        E = new u(uVar7, "12");
        F = new u(uVar7, "13");
        new u(uVar7, "14");
        new u(uVar7, "15");
        G = new u(uVar7, "16");
        H = new u(uVar7, "17");
        I = new u(uVar7, "18");
        J = new u(uVar7, "19");
        K = new u(uVar7, "20");
        u uVar8 = new u(uVar6, "1");
        L = new u(uVar8, "1");
        M = new u(uVar8, "2");
        N = new u(uVar8, "3");
        O = new u(uVar8, "4");
        P = new u(uVar8, "5");
        Q = new u(uVar8, "6");
        R = new u(uVar8, "7");
        new u("1.2.840.10040.4.1");
        new u("1.2.840.10040.4.3");
        u uVar9 = new u("1.3.133.16.840.63.0");
        new u(uVar9, "2");
        new u(uVar9, "3");
        new u(uVar9, "16");
        u uVar10 = new u("1.2.840.10046");
        new u(uVar10, "2.1");
        u uVar11 = new u(uVar10, "3");
        new u(uVar11, "1");
        new u(uVar11, "2");
        new u(uVar11, "3");
        new u(uVar11, "4");
        new u(uVar11, "5");
        new u(uVar11, "6");
        new u(uVar11, "7");
        new u(uVar11, "8");
        u uVar12 = new u(new u("1.3.133.16.840.9.44"), "1");
        new u(uVar12, "1");
        new u(uVar12, "2");
    }
}
