package defpackage;

/* JADX INFO: loaded from: classes3.dex */
public interface uhd {
    public static final u A;
    public static final u B;
    public static final u C;
    public static final u D;
    public static final u E;
    public static final u F;
    public static final u G;
    public static final u a;
    public static final u b;
    public static final u c;
    public static final u d;
    public static final u e;
    public static final u f;
    public static final u g;
    public static final u h;
    public static final u i;
    public static final u j;
    public static final u k;
    public static final u l;
    public static final u m;
    public static final u n;
    public static final u o;
    public static final u p;
    public static final u q;
    public static final u r;
    public static final u s;
    public static final u t;
    public static final u u;
    public static final u v;
    public static final u w;
    public static final u x;
    public static final u y;
    public static final u z;

    static {
        u uVar = new u("1.3.132.0");
        a = new u(uVar, "1");
        b = new u(uVar, "2");
        c = new u(uVar, "3");
        d = new u(uVar, "4");
        e = new u(uVar, "5");
        f = new u(uVar, "6");
        g = new u(uVar, "7");
        h = new u(uVar, "8");
        i = new u(uVar, "9");
        j = new u(uVar, "10");
        k = new u(uVar, "15");
        l = new u(uVar, "16");
        m = new u(uVar, "17");
        n = new u(uVar, "22");
        o = new u(uVar, "23");
        p = new u(uVar, "24");
        q = new u(uVar, "25");
        r = new u(uVar, "26");
        s = new u(uVar, "27");
        t = new u(uVar, "28");
        u = new u(uVar, "29");
        v = new u(uVar, "30");
        w = new u(uVar, "31");
        x = new u(uVar, "32");
        y = new u(uVar, "33");
        z = new u(uVar, "34");
        A = new u(uVar, "35");
        B = new u(uVar, "36");
        C = new u(uVar, "37");
        D = new u(uVar, "38");
        E = new u(uVar, "39");
        F = u5h.L;
        G = u5h.R;
        u uVar2 = new u("1.3.132.1");
        new u(uVar2, "11.0");
        new u(uVar2, "11.1");
        new u(uVar2, "11.2");
        new u(uVar2, "11.3");
        new u(uVar2, "14.0");
        new u(uVar2, "14.1");
        new u(uVar2, "14.2");
        new u(uVar2, "14.3");
        new u(uVar2, "15.0");
        new u(uVar2, "15.1");
        new u(uVar2, "15.2");
        new u(uVar2, "15.3");
        new u(uVar2, "16.0");
        new u(uVar2, "16.1");
        new u(uVar2, "16.2");
        new u(uVar2, "16.3");
    }
}
