package defpackage;

import defpackage.mq5;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Set;

/* JADX INFO: loaded from: classes3.dex */
public final class xqe {
    public static final mq5 a;
    public static final mq5 b;
    public static final mq5 c;
    public static final mq5 d;
    public static final mq5 e;
    public static final mq5 f;
    public static final mq5 g;
    public static final Set<mq5> h;
    public static final Set<mq5> i;
    public static final a62 j;
    public static final a62 k;
    public static final a62 l;
    public static final a62 m;
    public static final a62 n;
    public static final a62 o;
    public static final a62 p;
    public static final a62 q;
    public static final a62 r;
    public static final a62 s;
    public static final Set<a62> t;
    public static final Set<a62> u;
    public static final Set<a62> v;
    public static final a62 w;
    public static final a62 x;
    public static final a62 y;
    public static final a62 z;

    static {
        mq5 mq5Var = new mq5("kotlin");
        a = mq5Var;
        mq5 mq5VarA = mq5Var.a(n8a.h("reflect"));
        b = mq5VarA;
        mq5 mq5VarA2 = mq5Var.a(n8a.h("collections"));
        c = mq5VarA2;
        mq5Var.a(n8a.h("sequences"));
        mq5 mq5VarA3 = mq5Var.a(n8a.h("ranges"));
        d = mq5VarA3;
        mq5 mq5VarA4 = mq5Var.a(n8a.h("jvm"));
        mq5Var.a(n8a.h("annotations")).a(n8a.h("jvm"));
        mq5VarA4.a(n8a.h("internal"));
        mq5VarA4.a(n8a.h("functions"));
        mq5 mq5VarA5 = mq5Var.a(n8a.h("annotation"));
        e = mq5VarA5;
        mq5 mq5VarA6 = mq5Var.a(n8a.h("internal"));
        mq5VarA6.a(n8a.h("ir"));
        mq5 mq5VarA7 = mq5Var.a(n8a.h("coroutines"));
        f = mq5VarA7;
        mq5VarA7.a(n8a.h("intrinsics"));
        g = mq5Var.a(n8a.h("enums"));
        mq5Var.a(n8a.h("contracts"));
        mq5 mq5VarA8 = mq5Var.a(n8a.h("concurrent")).a(n8a.h("atomics"));
        mq5Var.a(n8a.h("test"));
        mq5Var.a(n8a.h("text"));
        h = ut0.I0(new mq5[]{mq5Var, mq5VarA2, mq5VarA3, mq5VarA5});
        i = ut0.I0(new mq5[]{mq5Var, mq5VarA2, mq5VarA3, mq5VarA5, mq5VarA, mq5VarA6, mq5VarA7, mq5VarA8});
        yqe.a("Nothing");
        j = yqe.a("Unit");
        k = yqe.a("Any");
        l = yqe.a("Enum");
        yqe.a("Annotation");
        m = yqe.a("Array");
        a62 a62VarA = yqe.a("Boolean");
        a62 a62VarA2 = yqe.a("Char");
        a62 a62VarA3 = yqe.a("Byte");
        a62 a62VarA4 = yqe.a("Short");
        a62 a62VarA5 = yqe.a("Int");
        a62 a62VarA6 = yqe.a("Long");
        a62 a62VarA7 = yqe.a("Float");
        a62 a62VarA8 = yqe.a("Double");
        n = yqe.f(a62VarA3);
        o = yqe.f(a62VarA4);
        p = yqe.f(a62VarA5);
        q = yqe.f(a62VarA6);
        yqe.a("CharSequence");
        r = yqe.a("String");
        yqe.a("Throwable");
        yqe.a("Cloneable");
        yqe.e("KProperty");
        yqe.e("KMutableProperty");
        yqe.e("KProperty0");
        yqe.e("KMutableProperty0");
        yqe.e("KProperty1");
        yqe.e("KMutableProperty1");
        yqe.e("KProperty2");
        yqe.e("KMutableProperty2");
        s = yqe.e("KFunction");
        yqe.e("KClass");
        yqe.e("KCallable");
        yqe.e("KType");
        yqe.a("Comparable");
        yqe.a("Number");
        yqe.a("Function");
        Set<a62> setI0 = ut0.I0(new a62[]{a62VarA, a62VarA2, a62VarA3, a62VarA4, a62VarA5, a62VarA6, a62VarA7, a62VarA8});
        t = setI0;
        u = ut0.I0(new a62[]{a62VarA3, a62VarA4, a62VarA5, a62VarA6});
        Set<a62> set = setI0;
        int iV = kc9.V(t92.r0(set, 10));
        if (iV < 16) {
            iV = 16;
        }
        LinkedHashMap linkedHashMap = new LinkedHashMap(iV);
        for (Object obj : set) {
            linkedHashMap.put(obj, yqe.d(((a62) obj).f()));
        }
        yqe.c(linkedHashMap);
        Set<a62> setI02 = ut0.I0(new a62[]{n, o, p, q});
        v = setI02;
        Set<a62> set2 = setI02;
        int iV2 = kc9.V(t92.r0(set2, 10));
        LinkedHashMap linkedHashMap2 = new LinkedHashMap(iV2 >= 16 ? iV2 : 16);
        for (Object obj2 : set2) {
            linkedHashMap2.put(obj2, yqe.d(((a62) obj2).f()));
        }
        yqe.c(linkedHashMap2);
        Set<a62> set3 = t;
        Set<a62> set4 = v;
        LinkedHashSet linkedHashSetO = bbe.o(set3, set4);
        a62 a62Var = r;
        bbe.p(linkedHashSetO, a62Var);
        mq5 mq5Var2 = f;
        n8a n8aVarH = n8a.h("Continuation");
        mq5Var2.getClass();
        mq5 mq5Var3 = mq5.c;
        mq5.a.a(n8aVarH).a.c();
        yqe.b("Iterator");
        yqe.b("Iterable");
        yqe.b("Collection");
        yqe.b("List");
        yqe.b("ListIterator");
        yqe.b("Set");
        a62 a62VarB = yqe.b("Map");
        yqe.b("AbstractMap");
        yqe.b("MutableIterator");
        yqe.b("CharIterator");
        yqe.b("MutableIterable");
        yqe.b("MutableCollection");
        w = yqe.b("MutableList");
        yqe.b("MutableListIterator");
        x = yqe.b("MutableSet");
        a62 a62VarB2 = yqe.b("MutableMap");
        y = a62VarB2;
        a62VarB.d(n8a.h("Entry"));
        a62VarB2.d(n8a.h("MutableEntry"));
        yqe.a("Result");
        mq5 mq5Var4 = d;
        n8a n8aVarH2 = n8a.h("IntRange");
        mq5Var4.getClass();
        mq5.a.a(n8aVarH2).a.c();
        mq5.a.a(n8a.h("LongRange")).a.c();
        mq5.a.a(n8a.h("CharRange")).a.c();
        mq5 mq5Var5 = e;
        n8a n8aVarH3 = n8a.h("AnnotationRetention");
        mq5Var5.getClass();
        mq5.a.a(n8aVarH3).a.c();
        mq5.a.a(n8a.h("AnnotationTarget")).a.c();
        yqe.a("DeprecationLevel");
        z = new a62(g, n8a.h("EnumEntries"));
        bbe.p(bbe.p(bbe.p(bbe.p(bbe.o(set3, set4), a62Var), j), k), l);
    }
}
