{
  "type" : "record",
  "name" : "mobPageLoadInfo",
  "namespace" : "com.indeed.signals.schema.jobsearch",
  "fields" : [ {
    "name" : "jsvPage",
    "type" : [ "null", "string" ],
    "doc" : "The key of jsv for a given pageId, see https://link.indeed.tech/GLYAX3DG3 for the mappings",
    "default" : null
  }, {
    "name" : "pageId",
    "type" : [ "null", "string" ],
    "doc" : "The actual pageid",
    "default" : null
  }, {
    "name" : "mobtk",
    "type" : [ "null", "string" ],
    "doc" : "The tracking key for SERP and Homepage",
    "default" : null
  }, {
    "name" : "mobvjtk",
    "type" : [ "null", "string" ],
    "doc" : "The tracking key for ViewJob",
    "default" : null
  }, {
    "name" : "ctk",
    "type" : [ "null", "string" ],
    "doc" : "ctk of the user",
    "default" : null
  }, {
    "name" : "country",
    "type" : [ "null", "string" ],
    "doc" : "country code",
    "default" : null
  }, {
    "name" : "scrWidth",
    "type" : [ "null", "long" ],
    "doc" : "screen width",
    "default" : null
  }, {
    "name" : "scrHeight",
    "type" : [ "null", "long" ],
    "doc" : "screen height",
    "default" : null
  }, {
    "name" : "pixelRatio",
    "type" : [ "null", "float" ],
    "doc" : "pixel density",
    "default" : null
  }, {
    "name" : "scrRes",
    "type" : [ "null", "string" ],
    "doc" : "screen resolution, eg. 1920x1080",
    "default" : null
  }, {
    "name" : "scrOrientation",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "ScreenOrientation",
      "symbols" : [ "PORTRAIT", "LANDSCAPE" ],
      "default" : "PORTRAIT"
    } ],
    "doc" : "screen orientation",
    "default" : null
  } ],
  "logEntryType" : "mobPageLoadInfo"
}