{
  "type" : "record",
  "name" : "saveJobClicks",
  "namespace" : "com.indeed.signals.schema.jobsearch",
  "fields" : [ {
    "name" : "mobtk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "tk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "originPage",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "SaveJobOriginPage",
      "symbols" : [ "serp", "viewjob", "homepage" ],
      "default" : "serp"
    } ],
    "default" : null
  }, {
    "name" : "action",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "SaveJobAction",
      "symbols" : [ "save", "unsave" ],
      "default" : "save"
    } ],
    "default" : null
  }, {
    "name" : "jobKey",
    "type" : [ "null", "string" ],
    "default" : null
  } ],
  "logEntryType" : "save_job_clicks"
}