{
  "type" : "record",
  "name" : "LightProfileOccupationSelectEvents",
  "namespace" : "com.indeed.signals.schema.cmijp",
  "fields" : [ {
    "name" : "tk",
    "type" : "string"
  }, {
    "name" : "parentTk",
    "type" : "string"
  }, {
    "name" : "ctk",
    "type" : "string"
  }, {
    "name" : "questionName",
    "type" : "string"
  }, {
    "name" : "selectMethod",
    "type" : {
      "type" : "enum",
      "name" : "LightProfileOccupationSelectEventsSelectType",
      "symbols" : [ "autoSuggest", "searchBar", "list" ]
    }
  } ],
  "logEntryType" : "LightProfileOccupationSelectEvents"
}