{
  "type" : "record",
  "name" : "AssistedApplyJobCardClickEvent",
  "namespace" : "com.indeed.signals.schema.jobcards",
  "fields" : [ {
    "name" : "jobKey",
    "type" : "string"
  }, {
    "name" : "logtk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "mobtk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "feedtk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "ctk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "accountId",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "hostId",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "HostId",
      "symbols" : [ "UNKNOWN", "MOBILE", "HOMEPAGE", "PASSPORT", "INDAPPLY", "SMARTAPPLY", "MYINDEED", "I2A_WEBAPP", "SJPW", "INCUBATOR", "CAREER_GUIDE_WEBAPP", "COMPANY_PAGES_WEBAPP" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  }, {
    "name" : "pageId",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "PageId",
      "symbols" : [ "UNKNOWN", "DESKTOP_SERP", "HOMEPAGE", "JP_MOBILE_SERP", "VIEWJOB" ],
      "default" : "UNKNOWN"
    } ],
    "default" : null
  } ],
  "logEntryType" : "assistedApplyJobCardClickEvent"
}