{
  "type" : "record",
  "name" : "RNGraphQLError",
  "namespace" : "com.indeed.signals.schema.reactnative",
  "doc" : "An error type logged by the react native platform when a GraphQL request fails.",
  "fields" : [ {
    "name" : "deviceProperties",
    "type" : {
      "type" : "record",
      "name" : "RNDevicePropertiesV4",
      "fields" : [ {
        "name" : "platform",
        "type" : {
          "type" : "enum",
          "name" : "RNPlatformsV4",
          "symbols" : [ "ios", "android" ]
        }
      }, {
        "name" : "osVersion",
        "type" : "string"
      }, {
        "name" : "appName",
        "type" : {
          "type" : "enum",
          "name" : "RNAppsV4",
          "symbols" : [ "jsma", "ema" ]
        }
      }, {
        "name" : "nativeAppVersion",
        "type" : "string"
      }, {
        "name" : "rnLibraryVersion",
        "type" : "string"
      }, {
        "name" : "rnAppBundleVersion",
        "type" : "string"
      }, {
        "name" : "manufacturer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "model",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "brand",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "systemName",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "buildVariant",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "environment",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "variant",
        "type" : [ "null", {
          "type" : "enum",
          "name" : "BuildVariant",
          "symbols" : [ "debug", "release" ]
        } ],
        "default" : null
      }, {
        "name" : "env",
        "type" : [ "null", {
          "type" : "enum",
          "name" : "Environment",
          "symbols" : [ "qa", "prod" ]
        } ],
        "default" : null
      }, {
        "name" : "isIpad",
        "type" : "boolean"
      } ]
    }
  }, {
    "name" : "query",
    "type" : "string"
  }, {
    "name" : "messages",
    "type" : {
      "type" : "array",
      "items" : "string"
    }
  }, {
    "name" : "variables",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "operationName",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "provider",
    "type" : "string"
  }, {
    "name" : "ctk",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "accountId",
    "type" : [ "null", "string" ],
    "default" : null
  } ],
  "logEntryType" : "rnGraphQLError"
}