{
  "type" : "record",
  "name" : "RNRenderErrorV4",
  "namespace" : "com.indeed.signals.schema.reactnative",
  "doc" : "An error type logged by the react native platform when the app fails to render.",
  "fields" : [ {
    "name" : "deviceProperties",
    "type" : {
      "type" : "record",
      "name" : "RNDevicePropertiesV4",
      "fields" : [ {
        "name" : "platform",
        "type" : {
          "type" : "enum",
          "name" : "RNPlatformsV4",
          "symbols" : [ "ios", "android" ]
        }
      }, {
        "name" : "osVersion",
        "type" : "string"
      }, {
        "name" : "appName",
        "type" : {
          "type" : "enum",
          "name" : "RNAppsV4",
          "symbols" : [ "jsma", "ema" ]
        }
      }, {
        "name" : "nativeAppVersion",
        "type" : "string"
      }, {
        "name" : "rnLibraryVersion",
        "type" : "string"
      }, {
        "name" : "rnAppBundleVersion",
        "type" : "string"
      }, {
        "name" : "manufacturer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "model",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "brand",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "systemName",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "buildVariant",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "environment",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "variant",
        "type" : [ "null", {
          "type" : "enum",
          "name" : "BuildVariant",
          "symbols" : [ "debug", "release" ]
        } ],
        "default" : null
      }, {
        "name" : "env",
        "type" : [ "null", {
          "type" : "enum",
          "name" : "Environment",
          "symbols" : [ "qa", "prod" ]
        } ],
        "default" : null
      }, {
        "name" : "isIpad",
        "type" : "boolean"
      } ]
    }
  }, {
    "name" : "message",
    "type" : "string"
  }, {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "stack",
    "type" : "string"
  }, {
    "name" : "componentStack",
    "type" : "string"
  }, {
    "name" : "provider",
    "type" : [ "null", "string" ]
  }, {
    "name" : "providerId",
    "type" : [ "null", {
      "type" : "enum",
      "name" : "ProviderId",
      "symbols" : [ "ViewJob", "Onboarding", "AceChat", "AceHub", "HomePage", "InterviewPrep", "ProfileForms", "Unknown", "Pathfinder", "Messaging" ],
      "default" : "Unknown"
    } ],
    "default" : null
  }, {
    "name" : "grps",
    "type" : [ "null", "string" ],
    "default" : null
  } ],
  "unstable_metrics" : [ {
    "name" : "reactnative.provider.renderError",
    "tags" : [ "providerId", "deviceProperties.platform", "deviceProperties.variant", "deviceProperties.env" ]
  } ],
  "logEntryType" : "rnRenderError"
}