{
  "type" : "record",
  "name" : "NativeHttpMetricsV7",
  "namespace" : "com.indeed.signals.schema.jsma",
  "fields" : [ {
    "name" : "device",
    "type" : {
      "type" : "record",
      "name" : "NativeDeviceV7",
      "fields" : [ {
        "name" : "platform",
        "type" : {
          "type" : "enum",
          "name" : "PlatformsV7",
          "symbols" : [ "IOS", "ANDROID" ]
        }
      }, {
        "name" : "manufacturer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "model",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "advertisingId",
        "type" : [ "null", "string" ]
      } ]
    }
  }, {
    "name" : "properties",
    "type" : {
      "type" : "record",
      "name" : "NativeEventPropertiesV7",
      "fields" : [ {
        "name" : "appId",
        "type" : {
          "type" : "enum",
          "name" : "NativeAppIdsV7",
          "symbols" : [ "TEST", "JOB_SEARCH_ANDROID", "JOB_SEARCH_IOS", "HQM_EMPLOYER_IOS" ],
          "default" : "TEST"
        }
      }, {
        "name" : "appVersion",
        "type" : "string"
      }, {
        "name" : "appBuildNum",
        "type" : "long"
      }, {
        "name" : "appVariant",
        "type" : "string"
      }, {
        "name" : "appEnvironment",
        "type" : "string"
      }, {
        "name" : "appCountry",
        "type" : [ "null", "string" ]
      }, {
        "name" : "ipCountry",
        "type" : [ "null", "string" ]
      }, {
        "name" : "osVersion",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "clientEventId",
        "type" : "string"
      }, {
        "name" : "appInstallId",
        "type" : "string"
      }, {
        "name" : "appSessionId",
        "type" : "string"
      }, {
        "name" : "sessionId",
        "type" : "string"
      }, {
        "name" : "clientCreatedTimestamp",
        "type" : {
          "type" : "long",
          "logicalType" : "timestamp-millis"
        }
      }, {
        "name" : "groups",
        "type" : {
          "type" : "array",
          "items" : "string"
        }
      }, {
        "name" : "accountId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "deviceId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "userLocale",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "deviceOrientation",
        "type" : {
          "type" : "enum",
          "name" : "DeviceOrientationsV7",
          "symbols" : [ "LANDSCAPE", "PORTRAIT" ]
        }
      } ]
    }
  }, {
    "name" : "url",
    "type" : "string"
  }, {
    "name" : "method",
    "type" : "string"
  }, {
    "name" : "request",
    "type" : {
      "type" : "record",
      "name" : "NativeHttpRequestDebugV7",
      "fields" : [ {
        "name" : "timestamp",
        "type" : {
          "type" : "long",
          "logicalType" : "timestamp-millis"
        }
      }, {
        "name" : "headerLength",
        "type" : "long"
      }, {
        "name" : "cookiesLength",
        "type" : "long"
      }, {
        "name" : "referrer",
        "type" : [ "null", "string" ]
      }, {
        "name" : "errDomain",
        "type" : [ "null", "string" ]
      }, {
        "name" : "errCode",
        "type" : [ "null", "long" ]
      } ]
    }
  }, {
    "name" : "response",
    "type" : [ "null", {
      "type" : "record",
      "name" : "NativeHttpResponseDebugV7",
      "fields" : [ {
        "name" : "timestamp",
        "type" : {
          "type" : "long",
          "logicalType" : "timestamp-millis"
        }
      }, {
        "name" : "headerLength",
        "type" : "long"
      }, {
        "name" : "contentLength",
        "type" : "long"
      }, {
        "name" : "contentType",
        "type" : "string"
      }, {
        "name" : "setCookiesLength",
        "type" : "long"
      }, {
        "name" : "statusCode",
        "type" : "long"
      }, {
        "name" : "errDomain",
        "type" : [ "null", "string" ]
      }, {
        "name" : "errCode",
        "type" : [ "null", "long" ]
      } ]
    } ]
  }, {
    "name" : "responseLatencyMs",
    "type" : "long"
  }, {
    "name" : "message",
    "type" : "string"
  } ],
  "logEntryType" : "jsmaNativeMetrics"
}