{
  "type" : "record",
  "name" : "NativeLifecycleV8V2",
  "namespace" : "com.indeed.signals.schema.jsma",
  "fields" : [ {
    "name" : "commonDetails",
    "type" : [ "null", {
      "type" : "record",
      "name" : "CommonEventDetails",
      "namespace" : "com.indeed.signals.common",
      "fields" : [ {
        "name" : "ipAddress",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    } ]
  }, {
    "name" : "device",
    "type" : {
      "type" : "record",
      "name" : "NativeDeviceV8",
      "fields" : [ {
        "name" : "platform",
        "type" : {
          "type" : "enum",
          "name" : "PlatformsV8",
          "symbols" : [ "IOS", "ANDROID" ]
        }
      }, {
        "name" : "manufacturer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "model",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "advertisingId",
        "type" : [ "null", "string" ]
      } ]
    }
  }, {
    "name" : "properties",
    "type" : {
      "type" : "record",
      "name" : "NativeEventPropertiesV8",
      "fields" : [ {
        "name" : "appId",
        "type" : {
          "type" : "enum",
          "name" : "NativeAppIdsV8",
          "symbols" : [ "TEST", "JOB_SEARCH_ANDROID", "JOB_SEARCH_IOS", "HQM_EMPLOYER_IOS" ],
          "default" : "TEST"
        }
      }, {
        "name" : "appVersion",
        "type" : "string"
      }, {
        "name" : "appBuildNum",
        "type" : "long"
      }, {
        "name" : "appVariant",
        "type" : "string"
      }, {
        "name" : "appEnvironment",
        "type" : "string"
      }, {
        "name" : "appCountry",
        "type" : [ "null", "string" ]
      }, {
        "name" : "ipCountry",
        "type" : [ "null", "string" ]
      }, {
        "name" : "osVersion",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "clientEventId",
        "type" : "string"
      }, {
        "name" : "appInstallId",
        "type" : "string"
      }, {
        "name" : "appSessionId",
        "type" : "string"
      }, {
        "name" : "sessionId",
        "type" : "string"
      }, {
        "name" : "clientCreatedTimestamp",
        "type" : {
          "type" : "long",
          "logicalType" : "timestamp-millis"
        }
      }, {
        "name" : "groups",
        "type" : {
          "type" : "array",
          "items" : "string"
        }
      }, {
        "name" : "accountId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "secondaryAccountId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "deviceId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "userLocale",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "deviceOrientation",
        "type" : {
          "type" : "enum",
          "name" : "DeviceOrientationsV8",
          "symbols" : [ "LANDSCAPE", "PORTRAIT" ]
        }
      } ]
    }
  }, {
    "name" : "eventName",
    "type" : "string"
  }, {
    "name" : "eventCount",
    "type" : "long"
  }, {
    "name" : "lastInstallTimestamp",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
  }, {
    "name" : "firstInstallTimestamp",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
  }, {
    "name" : "firstInstallVersion",
    "type" : "string"
  }, {
    "name" : "upgradedFromVersion",
    "type" : [ "null", "string" ]
  }, {
    "name" : "appStore",
    "type" : [ "null", "string" ]
  }, {
    "name" : "installerPackage",
    "type" : [ "null", "string" ]
  }, {
    "name" : "systemUserAgent",
    "type" : [ "null", "string" ]
  }, {
    "name" : "installReferrer",
    "type" : [ "null", "string" ]
  }, {
    "name" : "attributionToken",
    "type" : [ "null", "string" ]
  }, {
    "name" : "extraProperties",
    "type" : {
      "type" : "map",
      "values" : {
        "type" : "record",
        "name" : "JsmaDynamicProperty",
        "fields" : [ {
          "name" : "property",
          "type" : [ "null", "string", "long" ]
        } ]
      }
    },
    "default" : { }
  } ],
  "logEntryType" : "jsmaLifecycle"
}