{
  "type" : "record",
  "name" : "HttpError",
  "namespace" : "com.indeed.signals.schema.jsma.evergreen",
  "fields" : [ {
    "name" : "device",
    "type" : [ "null", {
      "type" : "record",
      "name" : "Device",
      "fields" : [ {
        "name" : "platform",
        "type" : {
          "type" : "enum",
          "name" : "Platforms",
          "symbols" : [ "IOS", "ANDROID", "WEB" ],
          "default" : "IOS"
        }
      }, {
        "name" : "manufacturer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "model",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "advertisingId",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    } ],
    "default" : null
  }, {
    "name" : "properties",
    "type" : [ "null", {
      "type" : "record",
      "name" : "EventProperties",
      "fields" : [ {
        "name" : "appId",
        "type" : {
          "type" : "enum",
          "name" : "AppIds",
          "symbols" : [ "TEST", "JOB_SEARCH_ANDROID", "JOB_SEARCH_IOS", "HQM_EMPLOYER_IOS", "EMPLOYER_ANDROID" ],
          "default" : "TEST"
        }
      }, {
        "name" : "appVersion",
        "type" : "string"
      }, {
        "name" : "appBuildNum",
        "type" : "long"
      }, {
        "name" : "appVariant",
        "type" : "string"
      }, {
        "name" : "appEnvironment",
        "type" : "string"
      }, {
        "name" : "appCountry",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ipCountry",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "osVersion",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "clientEventId",
        "type" : "string"
      }, {
        "name" : "appInstallId",
        "type" : "string"
      }, {
        "name" : "appSessionId",
        "type" : "string"
      }, {
        "name" : "sessionId",
        "type" : "string"
      }, {
        "name" : "clientCreatedTimestamp",
        "type" : "long"
      }, {
        "name" : "groups",
        "type" : {
          "type" : "array",
          "items" : "string"
        }
      }, {
        "name" : "accountId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "secondaryAccountId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "parentTk",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "ctk",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "deviceId",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "userLocale",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "indeedLocale",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "deviceOrientation",
        "type" : {
          "type" : "enum",
          "name" : "DeviceOrientations",
          "symbols" : [ "LANDSCAPE", "PORTRAIT" ]
        }
      } ]
    } ],
    "default" : null
  }, {
    "name" : "url",
    "type" : "string"
  }, {
    "name" : "method",
    "type" : "string"
  }, {
    "name" : "requestDebug",
    "type" : {
      "type" : "record",
      "name" : "HttpRequestDebug",
      "fields" : [ {
        "name" : "timestamp",
        "type" : "long"
      }, {
        "name" : "headerLength",
        "type" : "long"
      }, {
        "name" : "cookiesLength",
        "type" : "long"
      }, {
        "name" : "referrer",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "errDomain",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "errCode",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "networkInterface",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    }
  }, {
    "name" : "responseDebug",
    "type" : [ "null", {
      "type" : "record",
      "name" : "HttpResponseDebug",
      "fields" : [ {
        "name" : "timestamp",
        "type" : "long"
      }, {
        "name" : "headerLength",
        "type" : "long"
      }, {
        "name" : "contentLength",
        "type" : "long"
      }, {
        "name" : "contentType",
        "type" : "string"
      }, {
        "name" : "setCookiesLength",
        "type" : "long"
      }, {
        "name" : "statusCode",
        "type" : "long"
      }, {
        "name" : "errDomain",
        "type" : [ "null", "string" ],
        "default" : null
      }, {
        "name" : "errCode",
        "type" : [ "null", "long" ],
        "default" : null
      } ]
    } ],
    "default" : null
  }, {
    "name" : "message",
    "type" : "string"
  } ],
  "logEntryType" : "jsmaNativeHttpError"
}